### ISSUE TITLE
Add js embed to json response

### ISSUE THREAD

**Issue by crudo1f** [Giphy/GiphyAPI#100]
I think it would be really nice to add an attribute to the response json which holds html which can be used to directly embed the giphy 'player' (e.g. the code given in the 'JS Embed' share option).

Or did I miss a reason for not doing this?

**Comment by timfrietas** [comment]
Hey @crudo1f that's a good feature request so I put it in our feature request backlog!  Closing this out as we use Issues to track open bugs, but it does seem like a great idea!
