### ISSUE TITLE
Giphy Upload API

### ISSUE THREAD

**Issue by rbryan167** [Giphy/GiphyAPI#102]
I have tried using both base64 string or bytes of array, what type does the file parameter for the upload api accept? Can I directly uploud the GIF file directly without urls? We don't have a web service to temporary host the GIF file.

**Comment by timfrietas** [comment]
Hi @rbryan167 right now we only support binaries (e.g. .gif, .mp4).  You can upload files locally by using the "file" parameter.  I put in a feature request for base 64 support so hopefully that's something we offer soon!
