### ISSUE TITLE
Upload api- lack of parameter?

### ISSUE THREAD

**Issue by eleduarr** [Giphy/GiphyAPI#103]
Hi.
I see that the upload api has no time parameter, for example when a video is uploaded it can not be selected what part you want to make the gif. it was meant to do that? or just didn't considered?.

**Comment by timfrietas** [comment]
Hi @eleduarr right now that is intentional and V1 just processes the video as-is.  This is one of many features we are considering for future versions!

**Comment by llemurya** [comment]
Hello @timfrietas any changes on this issue, maybe you added this feature on production, because in the documentation is not specified about time parameter and duration. Thanks.
