### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

### ISSUE THREAD

**Issue by avipinto** [Giphy/GiphyAPI#105]
something changed on your servers and you are now returning the Access-Control-Allow-Origin header key twice which causes CORS requests to fail
look at your example utl from the docs http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=american+psycho
open dev tools and see it live
**response headers from the above link:**
Accept-Ranges:bytes
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Content-Type, Accept
Access-Control-Allow-Methods:GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Allow-Origin:* 
Age:0
Age:0
Cf-Railgun:b863fa4049 60.22 0.029666 0030 5f99
CF-RAY:2fadc4cf639235c0-LHR
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json
Date:Tue, 01 Nov 2016 07:52:42 GMT
Server:cloudflare-nginx
Transfer-Encoding:chunked
Vary:Accept-Encoding, Accept-Encoding
X-Robots-Tag:noindex

**Comment by Fdebijl** [comment]
Can confirm, Acces-Control-Allow-Origin header is present twice in Respone Header causing the error below

`XMLHttpRequest cannot load http://api.giphy.com/v1/gifs/random?api_key=REDACTED The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://exmaple.com' is therefore not allowed access.`

Full Response Header for reference.

`HTTP/1.1 200 OK`
`Date: Tue, 01 Nov 2016 10:57:37 GMT`
`Content-Type: application/json`
`Transfer-Encoding: chunked`
`Connection: keep-alive`
`Accept-Ranges: bytes`
`Access-Control-Allow-Credentials: true`
`Access-Control-Allow-Headers: Content-Type, Accept`
`Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS`
`Access-Control-Allow-Origin: *`
`Access-Control-Allow-Origin: *`
`Age: 0`
`Age: 0`
`Cf-Railgun: e4dd37cf22 69.69 0.031938 0030 5f99`
`Vary: Accept-Encoding, Accept-Encoding`
`X-Robots-Tag: noindex`
`Server: cloudflare-nginx`
`CF-RAY: 2faed3af47242bb2-AMS`
`Content-Encoding: gzip`

**Comment by timfrietas** [comment]
Hey all, 

Yep this is a bug, we should have a release out in a few hours to address it.  So sorry for the inconvenience!

**Comment by wleecarter** [comment]
I'm continuing to get this as well, but it only happens every "x" requests, where "x" is random:

![image](https://cloud.githubusercontent.com/assets/2816552/20121351/e5e2e8be-a5de-11e6-9eb0-ac957908f6c9.png)

If you look at any of the ones that succeeded, the 'Access-Control-Allow-Origin' value only appears once:

![image](https://cloud.githubusercontent.com/assets/2816552/20121461/a2136aea-a5df-11e6-8647-07b7aa2c9289.png)

However, for the one that failed, it appears twice:

![image](https://cloud.githubusercontent.com/assets/2816552/20121469/abdccefe-a5df-11e6-9377-7b8b5775761a.png)

Is there a server that maybe wasn't patched?

**Comment by TetraEtc** [comment]
If you're load balancing API calls, it might be a case with a particular instance is still sending these wrong.

**Comment by temapavloff** [comment]
Hi guys,

We still have this headers issue making cross-origin requests to your API from JS in browser. It don't even pass `Access-Control-Allow-Origin` header in preflight response. Here is log from Chrome console:

```
Request URL: http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=thank%2Byou
Request Method: OPTIONS
Status Code: 204 No Content
Remote Address: 151.101.37.127:80

Response Headers
Accept-Ranges: bytes
Accept-Ranges: bytes
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Accept
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Age: 0
Age: 0
Connection: keep-alive
Date: Mon, 14 Nov 2016 08:52:16 GMT
Via: 1.1 varnish
X-Cache: MISS
X-Cache-Hits: 0
X-Cachiness-Edge-Timeout: 1200.000
X-Cachiness-Origin-Respect: respect_origin
X-Cachiness-Rule-Name: fastly_default
X-Rule-Debug: 1
X-Served-By: cache-ams4422-AMS
X-Timer: S1479113536.422682,VS0,VE92

Request Headers
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6,de;q=0.4
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: GET
Connection: keep-alive
Host: api.giphy.com
Origin: http://staff.timeweb.loc
Referer: http://staff.timeweb.loc/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36

Query String Parameters
api_key: dc6zaTOxFJmzC
tag: thank+you
```

As you can see we always get some duplicating headers and never get any `Access-Control-Allow-Origin`.

Can you tell us roughly when you'll make this fix?

**Comment by timfrietas** [comment]
Hello everyone,

This issue should hopefully be resolved.  We're still monitoring the situation before we close this issue to ensure the fix in place is permanent.

**Comment by temapavloff** [comment]
Still getting this issue :-(

**Comment by timfrietas** [comment]
Can you share which endpoint you are hitting @temapavloff?

**Comment by temapavloff** [comment]
@timfrietas the same as in my previous comment, you can see whole log there.

**Comment by timfrietas** [comment]
Thanks, @temapavloff that's a help!  If you are willing to share your Chrome console output again that would help us isolate the issue.

**Comment by poopsplat** [comment]
Also getting the same issue testing, which I thought might have been due to a limitation when using the public key, because it just started happening after working consistently for a full day.

Console output: http://d.pr/i/X36E
Testing url: http://codepen.io/poopsplat/pen/4034f2b2396793eeb543b5d3384d07f7/

**Comment by timfrietas** [comment]
@poopsplat your Codepen has a syntax error; you have an invalid API request `&api_keyc=dc6zaTOxFJmzC`  instead of `&api_key=dc6zaTOxFJmzC`, so you should be getting 401s

@temapavloff are you still having the same issue?

**Comment by poopsplat** [comment]
@timfrietas oh brother, my bad! Thanks for finding that!

**Comment by timfrietas** [comment]
This should now be completely resolved.

**Comment by KarthicRaj** [comment]
@timfrietas - what was done to fix this. I am facing similar issues with our springboot API

**Comment by JitendraShinde** [comment]
Im getting similar issue, could anyone please  elaborate the fix? Lots of article but no clear fix.

**Comment by shuklajay117** [comment]
Even after it's closed for 4 years, I'm still struggling to fix this issue. Please help if anyone finds the solution.
