### ISSUE TITLE
Sticker endpoint returns the same results for Translate and Random every time

### ISSUE THREAD

**Issue by jrub1** [Giphy/GiphyAPI#107]
I'm not sure if this is intentional or not, but while the GIF translate (and Random) endpoint gives pretty much a different gif every time (for something that has more than one possible result), the Sticker endpoint seems to return the same one every time. I verified this by refreshing the example calls on the documentation.

**Comment by timfrietas** [comment]
Nope, that's a bug!  Thanks for reporting, we will ship a fix ASAP.

**Comment by ramiel** [comment]
It's incredible...but I need this! When will it be fixed?

**Comment by fab1o** [comment]
I just reported a duplicated issue https://github.com/Giphy/GiphyAPI/issues/171

**Comment by Sixuan** [comment]
Sorry for the delay, this has been fixed today.
