### ISSUE TITLE
emebed.js unsets $

### ISSUE THREAD

**Issue by pozsi** [Giphy/GiphyAPI#109]
[Previously](https://github.com/Giphy/GiphyAPI/issues/8) embed.js used to redefine `$` to `window.jQuery`, now it assigns `undefined` to it and then proceeds to load 1.10.2, overwriting any existing instances of a different version, wiping all loaded plugins in the process.

**Comment by dfinkler** [comment]
Hi @pozsi at this time we do not recommend that developers use our embed.js code to develop again.  We didnt intend for this bit of code to function outside of our environment so cannot guarantee that it will behave as you may need it to.  We're working on improving our embed offerings and we'll announce any updates in that arena when they are out! Thanks
