### ISSUE TITLE
image_url is not secure

### ISSUE THREAD

**Issue by raybogman** [Giphy/GiphyAPI#110]
is there a workaround to get the 'image_url' callback secure.
default the xhr callback is http:// of the image.

would it be possible to create a "image_url_sec" with will return a https:// url

**Comment by nkhoshini** [comment]
HI @raybogman, thanks for the feedback.

When calling the API using HTTPS, you'll receive HTTPS url's back.
EX:

https://api.giphy.com/v1/gifs/search?q=funny+cat&api_key=dc6zaTOxFJmzC

sends back URL's like:
https://media1.giphy.com/media/iuHaJ0D7macZq/200.gif

Let us know if that helps,
Regards,
Nima

**Comment by raybogman** [comment]
Thanx Nima,

well the thing is when using XHR the output is http instead of https

here a small script I use

$(function(){var a=$.get("https://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=funny+penguin");a.done(function(a){$(".gif-bg").css("background-image","url("+a.data.image_url+")")})});

this will output

Mixed Content: The page at 'https://url.com/result/ed8526a4-ae54-42de-b09d-780c304a6c07' was loaded over HTTPS, but requested an insecure image 'http://media4.giphy.com/media/37mHwC7vxU5fq/giphy.gif'. This content should also be served over HTTPS.

**Comment by nkhoshini** [comment]
Ok, it looks like the random endpoint is not observing the rule of spitting back secure URL's. I assume if you were to test with the search or trending endpoints you won't be running into those XHR errors correct?

I'll have our team take a look into why the random endpoint is giving HTTP results.

Cheers,
Nima

**Comment by raybogman** [comment]
Hi Nima,

Just checkin' if there is a update on the non secure url

Regards
Ray

**Comment by dfinkler** [comment]
@raybogman we're working on getting a fix out but in the meanwhile it's safe to assume you can access all of our renditions via HTTPS.  I'll let you know when a fix is out - sorry it's taken a minute

**Comment by avanwor** [comment]
Use the "upgrade-insecure-requests" CSP directive in the HTML head

`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

My issue was the embed_url link (https) redirects to a giffy s3 bucket (http) causing a 'mixed content' error. By setting the "Content-Security-Policy" to "upgrade-insecure-requests", all requests made from your html will be over https (except for 'navigational') 
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content

**Comment by lenmorld** [comment]
the `<meta>` solution worked for me thanks!
https://codesandbox.io/embed/autumn-glitter-k3oyvolr65?fontsize=14

**Comment by shwetaatgiphy** [comment]
Hey All,

You should see all https links to assets with the random endpoint as well now. 
Please feel free to reopen the issue and let us know if that's not the case though for you. 
Thank you 🙂
