### ISSUE TITLE
Search gifs by length / loop rate?

### ISSUE THREAD

**Issue by theaged** [Giphy/GiphyAPI#113]
Hey guys,

 I'm looking for a way to search for gifs by length and it doesn't appear that there is currently a way to do so. I figured the closest thing I can get to this is to search for a desired gif, retrieve the .mp4 source for that gif, and then parse the results until one with a desired length is found. 

 Is there a better way to go about this?

 Thanks!

**Comment by dfinkler** [comment]
hi @theaged we currently don't have faceted search enabled for these attributes but it's on the road map and should be available in the near future.  We'll make an announcement when this feature goes live in the API

**Comment by wpp** [comment]
Hi!

Are you able to give a more concrete timeline for this? Doesn't look like it's been released yet, right? https://developers.giphy.com/docs/

Cheers
