### ISSUE TITLE
Search by category

### ISSUE THREAD

**Issue by dczaretsky** [Giphy/GiphyAPI#114]
I'd like to know if it is possible to search by category through the API, the same functionality available on the website. Searching by keywords is somewhat limiting. Thanks.

**Comment by nkhoshini** [comment]
We currently do not have support for searching by category. Leaving this issue open as an enhancement for future releases of the API.

**Comment by thePsguy** [comment]
bump

**Comment by shwetaatgiphy** [comment]
Hi @dczaretsky , @thePsguy 

GIPHY now has an [endpoint](https://developers.giphy.com/docs/api/endpoint#categories) that gives you all the categories and subcategories on our end. You can then pass the categories as tags to the search endpoint. 

Hope this helps. 🙂
