### ISSUE TITLE
How to implement pagination for trending API ?

### ISSUE THREAD

**Issue by passiondroid** [Giphy/GiphyAPI#116]
I am sending below request 

http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&offset=0

Then  after user scrolls to the end of the list i am sending new request with offset 1

http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&offset=1

But both time, i am receiving the same json response

**Comment by quiqueqs** [comment]
@passiondroid Did you find a solution for this?

**Comment by passiondroid** [comment]
@quiqueqs No, I dont know why giphy guys are not looking at it or explaining if there is any other way to do pagination.

**Comment by szaveri** [comment]
@passiondroid 

The **offset** value is not the same as a page value, it returns the next "X" number of GIFs up to the limit given (default 25). In your example the first API call would retrieve GIF 1-25, the second would return 2-26. 

In your case, you would want your second page to actually call **offset=25**.

**Comment by nkhoshini** [comment]
@passiondroid apologies for the delay here, the explanation provided by @szaveri is exactly correct. Let us know if you have any other questions.
