### ISSUE TITLE
Possibly incorrect Accept header parsing from your servers or CDN

### ISSUE THREAD

**Issue by megamattron** [Giphy/GiphyAPI#117]
With an accept header that lists ```*/*``` with a lower priority you return a redirect, for example:

```
curl -I -H "Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" http://media4.giphy.com/media/IThjAlJnD9WNO/200.mp4
```

Returns these headers:
```
HTTP/1.1 302 Found
Retry-After: 0
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 06 Apr 2017 13:55:42 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-iad2138-IAD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1491486942.130181,VS0,VE0
Access-Control-Allow-Origin: *
Location: /media/IThjAlJnD9WNO/giphy.gif
Cache-Control: max-age=86400
```

But something like:
```
curl -I -H "Accept: */*" http://media4.giphy.com/media/IThjAlJnD9WNO/200.mp4
```

You return the actual file:
```
HTTP/1.1 200 OK
Last-Modified: Wed, 27 Jul 2016 16:51:42 GMT
ETag: "6cb53b0cde5c3944ac28f04190dec1ac"
Content-Type: video/mp4
Content-Length: 158037
Accept-Ranges: bytes
Date: Thu, 06 Apr 2017 13:57:22 GMT
Via: 1.1 varnish
Age: 2433011
Connection: keep-alive
X-Served-By: cache-iad2638-IAD
X-Cache: HIT
X-Cache-Hits: 5
X-Timer: S1491487042.550282,VS0,VE0
Access-Control-Allow-Origin: *
Cache-Control: max-age=86400
```

Not sure if this is by design but it caused one of my servers using the API to stop working because it was sending the accept header shown in the first example.

**Comment by nkhoshini** [comment]
Hi @megamattron, by specifying text/html in your request here
```bash
curl -I -H "Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" http://media4.giphy.com/media/IThjAlJnD9WNO/200.mp4
```
You will receive an HTML response. 

Removing the text/html portion will give you the actual file:
```bash
curl -I -H "Accept: image/gif, image/jpeg, *; q=.2, */*; q=.2" http://media4.giphy.com/media/IThjAlJnD9WNO/200.mp4
```
```bash
HTTP/1.1 200 OK
Last-Modified: Wed, 27 Jul 2016 16:51:42 GMT
ETag: "6cb53b0cde5c3944ac28f04190dec1ac"
Content-Type: video/mp4
Content-Length: 158037
Accept-Ranges: bytes
Date: Tue, 18 Apr 2017 14:34:06 GMT
Via: 1.1 varnish
Age: 3472015
Connection: keep-alive
X-Served-By: cache-iad2136-IAD
X-Cache: HIT
X-Cache-Hits: 12
X-Timer: S1492526046.479934,VS0,VE0
Access-Control-Allow-Origin: *
Cache-Control: max-age=86400
```

**Comment by megamattron** [comment]
Thanks @nkhoshini. The main problem is that the first accept header seems to be the default for Java so probably a bunch of Java clients of the giphy API broke recently. Or at least mine did.

**Comment by nkhoshini** [comment]
I see, that makes sense. Which Java library are you using? Is there support for disabling or overriding the default header behavior?

**Comment by megamattron** [comment]
I was using commons.io.FileUtils (https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html) to copy the URL to a file like so: ```FileUtils.copyURLToFile(new URL(mp4Url), mp4File);``` but that stopped working recently. I couldn't figure out a way to modify headers for FileUtils so I switched to another library entirely. It's built into the old framework I use so it's probably not to helpful for anyone else reading this, but here it is in case: https://www.playframework.com/documentation/1.1/api/play/libs/WS.html So now I do something like:

```
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        WS.WSRequest wsRequest = WS.url(url);
        wsRequest.setHeader("Accept", "*/*");
        InputStream stream = wsRequest.get().getStream();
        IOUtils.copy(stream, baos);
```
