### ISSUE TITLE
app crash in risultati search

### ISSUE THREAD

**Issue by huftre** [Giphy/GiphyAPI#122]
When I try to search gif with a word, for example, "woman" app freezes, it freezes and the console does not return anything. By pausing the debug here is what goes out
Can I have a personal email for you to write?
![b68d1d18-3707-11e7-9021-71452829aed8](https://cloud.githubusercontent.com/assets/15199043/25996419/7e124124-3717-11e7-9a99-0a0e23ad2e73.png)

**Comment by dfinkler** [comment]
hi @huftre I am not sure how the bug you are filing here is related to the Giphy API.  It sounds like the client you are using to interface with the Giphy API is having issues as a tag search for "woman" is working as expected:

http://api.giphy.com/v1/gifs/search?q=woman&api_key=4OMJYpPoYwVpe
