### ISSUE TITLE
Still images returned from the api not working

### ISSUE THREAD

**Issue by infomofo** [Giphy/GiphyAPI#123]
Still images returned by the api don't seem to be working.

From the sample query in your README:

http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=dc6zaTOxFJmzC

This returns several images, the first record in this format

```
images: {
fixed_height: {
url: "http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/200.gif",
width: "487",
height: "200",
size: "800927",
mp4: "http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/200.mp4",
mp4_size: "73376",
webp: "http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/200.webp",
webp_size: "90648"
},
fixed_height_still: {
url: "http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/200_s.gif",
width: "487",
height: "200",
size: "46892"
},
...
```

However, when I use that fixed_height_still url it is responding with a 302 found response redirecting me from

http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/200_s.gif 

to

http://media1.giphy.com/media/3ohzdZ2EG9f8uC0gDK/giphy.gif

which is not a still image, it's an animated gif.

I believe this used to work, but it doesn't seem to be anymore.

**Comment by dfinkler** [comment]
@infomofo thanks for the bug report - I confirmed the behavior you are seeing and we're looking into a fix.

**Comment by dfinkler** [comment]
here's a sample cURL that illustrates how to get a binary gif file via the http accept header

```curl -X GET   http://media1.giphy.com/media/yAqdjThdDEMF2/giphy.gif   -H 'accept: : image/*'```

**Comment by infomofo** [comment]
Thanks for that, but this workaround doesn't work for my use case, which is displaying these still images on a webapp. If I just load that image in chrome it displays the animated version.

**Comment by dfinkler** [comment]
hi @infomofo if you change the GET request that fetches the still GIF to use the accept header you will be served back the correct still rendition.
