### ISSUE TITLE
Search by not a rating

### ISSUE THREAD

**Issue by leighmcculloch** [Giphy/GiphyAPI#126]
In the README it says the search can be optionally filtered by a rating.

>rating - (optional) limit results to those rated (y,g, pg, pg-13 or r).

Could it be possible to search by not a rating, so it would be possible to retrieve all results that are not rated `r`, which would return results y, g, pg, pg-13, and those not rated?

**Comment by leighmcculloch** [comment]
cc @wjdix

**Comment by dfinkler** [comment]
hi @leighmcculloch - at this time it's not possible to specify a filter based on rating.  We are exploring ways to do richer faceted search API.
