### ISSUE TITLE
Get the tags of GIFs in the response?

### ISSUE THREAD

**Issue by incyclum** [Giphy/GiphyAPI#127]
In my company we're developing a survey SaaS app based on chatbots.
The user can add GIFs in the conversation with the bot.

When a user insert a GIF we'd like to keep the associated tags for analytics and datamining.

E.g. the tags displayed at the bottom of the screenshot : http://i.imgur.com/OBbheDL.png

Thank you

**Comment by dfinkler** [comment]
Hi @incyclum please submit the app here 

```api.giphy.com/submit``` 

and our API partnerships team will do their best to assist.

**Comment by wmh** [comment]
Hi @dfinkler We had applied for a production key on the dashboard and can't find the tags in API responses. How do we submit the app to get the tags?

**Comment by lukeleeai** [comment]
Hello, I'd also love to get tags in responses. I think the link "http://api.giphy.com/submit" is expired. What should I do?
