### ISSUE TITLE
API Responses do not use image/gif MIME type.

### ISSUE THREAD

**Issue by Brodan** [Giphy/GiphyAPI#128]
When I reach out to a gif's URL that is returned by this API, I receive a bunch of HTML, and not a .gif.
This makes the API inapplicable to my use case because a URL to a '.gif' resource should return with a MIME type of `image/gif`, not `text/html`.

**Comment by dfinkler** [comment]
Hi @Brodan - if you add the header 

```accept: image/*```

You will get the binary GIF itself, not HTML.  Here's a sample cURL command that illustrates this 

```curl -X GET \
  http://media1.giphy.com/media/yAqdjThdDEMF2/giphy.gif \
  -H 'accept: : image/*' ```

**Comment by Brodan** [comment]
Hi @dfinkler,

Thanks for the response! Perhaps my question was unclear. Based on your response, it means I have to make two requests in order to get a .gif resource using the GiphyAPI. The first is to get the search results, and the second is to get the image binary using the URL in the search result.

Is this correct?
