### ISSUE TITLE
C# Example for docs

### ISSUE THREAD

**Issue by Yucked** [Giphy/GiphyAPI#130]
Here is a small example written in C# which displays all the results from the webpage;
```cs
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace GiphyDemo
{
    class Program
    { 
        static void Main(string[] args) => new Program().CoreAsync().GetAwaiter().GetResult();
        async Task CoreAsync()
        {
            var GetURL = await new HttpClient().GetAsync("http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=API-KEY-HERE&limit=5");
            var Content = await GetURL.Content.ReadAsStringAsync();
            Console.Write(Content);
        }
    }
}
```
Here is a bit more advanced example which uses Newtonsoft.Json to get data:
https://github.com/Yucked/Rick/blob/master/Rick/Modules/GiphyModule.cs
https://github.com/Yucked/Rick/blob/master/Rick/JsonModels/Giphy.cs
![](http://vvcap.com/img/mkbivhRpc5m.png)

**Comment by dfinkler** [comment]
hi @Yucked - thanks for sharing your code examples with us!  Let us know if you have any questions or issues using the Giphy API.
