### ISSUE TITLE
Render gifs in Swift

### ISSUE THREAD

**Issue by wahlforss** [Giphy/GiphyAPI#131]
Hey Giphy, I have a question not regarding your API. How do you render your gifs in Swift IOS?

**Comment by dfinkler** [comment]
Hi @wahlforss there's a number of image rendering libraries for Swift / iOS that support GIF rendering.  At this time GIPHY doesnt have a public SDK or code that I can share with you but I recommend you look into something like this:

https://github.com/kaishin/Gifu
