### ISSUE TITLE
Wrong URL format: httpss 

### ISSUE THREAD

**Issue by storix** [Giphy/GiphyAPI#132]
Hi,

Sometimes Giphy returns URLs in wrong format. For example, the following request

https://api.giphy.com/v1/gifs/search?q=colors&api_key=dc6zaTOxFJmzC

will return some URLs with `httpss` protocol. 

It seems this is just a typo (I mean the last redundant `s` character). Thanks.

**Comment by dfinkler** [comment]
hi @storix - thanks for the issues report.  we're looking into this and trying to replicate the bad behavior!

**Comment by dfinkler** [comment]
hi @storix 
thanks for the bug report - the API should be patched with a fix for this issue.
