### ISSUE TITLE
the API documentation has moved

### ISSUE THREAD

**Issue by hibaakel** [Giphy/GiphyAPI#133]
i can not find the new docs of GiphyAPI?!!!

**Comment by Yucked** [comment]
Here is the documentation: https://developers.giphy.com/docs/

**Comment by storix** [comment]
@Yucked And where is the upload api documentation?

**Comment by Yucked** [comment]
I couldn't find it in the link provided above so I'm assuming they haven't wrote it yet. @storix

**Comment by dfinkler** [comment]
@hibaakel @storix we're working on updating the public API documentation to work with the new developer portal docs we recently launched! stay tuned - we should have the upload docs migrated shortly.

**Comment by dfinkler** [comment]
quick update on this - we are working with a 3rd party developer to address a bug in a piece of software we use to help manage our infrastructure. Once this bug is addressed we will re-release the documentation and support public access to the upload api

**Comment by shwetaatgiphy** [comment]
Hi Everyone,

You can always navigate to our API and SDK documentation from this link - https://developers.giphy.com/
If you have any implementation questions, please feel free to email developers@giphy.com
Thank you! 🙂
