### ISSUE TITLE
Can I get specific Gif size json response ?

### ISSUE THREAD

**Issue by l376571926** [Giphy/GiphyAPI#135]
Is there a way can i get specific size json response ? I jus want fix_width size Gif, and other size I don't want response in json.
download 25 Gif json length 119kb
download 1 Gif json length 5kb
if i can reduce json length,json download and parse will be quickly,and gif show will be quickly also,thanks.

**Comment by dfinkler** [comment]
hi @l376571926 thanks for the feature request - at this time we dont have a way to only return certain renditions in the api response but this is a great feature request.  I've made a note of it and as soon as we have any details on when it will be available we will make an announcement.
