### ISSUE TITLE
Incorrect developer doc, ISO639-1 is language code not country code

### ISSUE THREAD

**Issue by simonzhexu** [Giphy/GiphyAPI#136]
https://developers.giphy.com/docs/#language-support says:
lang - specify default country for regional content; format is 2-letter ISO 639-1 country code

ISO 639-1 is really a language code, not country code.

**Comment by dfinkler** [comment]
Thanks for the note @simonzhexu - we'll update the documentation to be more correct.

**Comment by dfinkler** [comment]
fixed in the latest document update - thank you !
