### ISSUE TITLE
Unable to get direct MP4 output via API instead of HTML Output

### ISSUE THREAD

**Issue by OffSa** [Giphy/GiphyAPI#137]
Unable to get a direct Mp4 output via API instead getting Output with a HTML file

**Comment by dfinkler** [comment]
Hi @OffSa can you give us some more information about your issue?   

Are you having difficulties with an mp4 rendition of a GIF? 

Please take a look at our [rendition guide](https://developers.giphy.com/docs/) - it might be helpful!
