### ISSUE TITLE
Unable to set an offset in the trending endpoint.

### ISSUE THREAD

**Issue by pradyutbansal** [Giphy/GiphyAPI#138]
The search api allows you to give an offset, but trending does not.

**Comment by szaveri** [comment]
The documentation doesn't show the offset parameter but it should work just like search.

`http://api.giphy.com/v1/gifs/trending?offset=20&api_key=<YOUR KEY>`

**Comment by pradyutbansal** [comment]
Thanks for the prompt response. Can the documentation be updated so that
the use of the api may be maximised?

Best,
Pradyut Bansal

**Comment by dfinkler** [comment]
Hi @szaveri and @pradyutbansal thanks for the note - we'll update the documentation shortly

**Comment by dfinkler** [comment]
documentation updated - thanks for the note

**Comment by pradyutbansal** [comment]
Hi,

Hope all is well. I recently graduated from Macalester and will be losing
access to pbansal@macalester.edu if you wish to reach me, I am available at
pradyutbansal@gmail.com.

Hope to stay in touch.

Best,
Pradyut Bansal
