### ISSUE TITLE
Exact tag searching

### ISSUE THREAD

**Issue by rkmcdonnell** [Giphy/GiphyAPI#139]
Are there plans to incorporate an "exact match" flag into the search endpoint, such that only GIFs tagged with the exact query are returned?  For example, if I search for "happy feet", I end up getting a much larger list of GIFs than I would like, with results tagged with either "happy" or "feet" also included.  If this will be added as a feature in the future, what is the timeline?

**Comment by dfinkler** [comment]
hi @rkmcdonnell - we are working on extending the public search API, we have noted his feature request for exact phrase matching - stay tuned!
