### ISSUE TITLE
How to make a semi-private GIF?

### ISSUE THREAD

**Issue by kappaknight** [Giphy/GiphyAPI#141]
Does GIPHY currently have an option of a private URL that is also shareable?

I don't see why anyone would want to create a gif just for themselves... shouldn't the private option be "viewable, but not searchable" so it can be posted on FB if I have the link, but not searchable so anyone can summon it via a keyword?

**Comment by dfinkler** [comment]
Hi @kappaknight this should be possible using the giphy.com web application.  If you are having trouble please email support@giphy.com and they will be able to give you exact instructions on how!
