### ISSUE TITLE
Get short URL for Twitter posting

### ISSUE THREAD

**Issue by arminsal1** [Giphy/GiphyAPI#142]
My application is attempting to post to a tweet through Twitter's api that contains a gif obtained via Giphy's api, but the urls provided by the api don't seem to support Twitter's embedding. Is there a way to get the shortened url or some url that supports tweet embedding from the Giphy api?

**Comment by dfinkler** [comment]
Hi @arminsal1 can you provide more details on what link you are using when embedding the GIF and what endpoint you are using on Twitter's end?  Both the GIF URL and the shortened Bit.ly URL should properly embed in tweets so I'd need to know more specifics on what isn't working for you before we can debug further.

**Comment by arminsal1** [comment]
Hi @dfinkler sorry for the late reply! I'm using the POST statuses/update endpoint on Twitter's end and the passed status text is the URL string for the GIF found in the `object.images.fixed_height.url` object. The URL works fine for displaying GIFs within my own application but it won't embed when I post to Twitter, it just shows the link as a hyperlink.

**Comment by arminsal1** [comment]
@dfinkler Any updates?

**Comment by helderdek** [comment]
Same problem

**Comment by arminsal1** [comment]
@helderdek What worked for me: Use the bitly_url from the query for your twitter post. It'll automatically embed.

**Comment by helderdek** [comment]
@arminsal1 thanks!!
 I was using _/v1/gifs/random_ and the _bitly_url_ dont come in the JSON, so I get the ID from the gif and pass to _/v1/gifs/random_ then _bitly_url_ appear

**Comment by dellkurd** [comment]
hi 

The best new free url shorteners https://htt.nu
Support QR URL Code 
Full free php API 
Full Statistic ( Location,Referrer,Browser,Platform,Device,mobile ) 
Unlimited URL - Free Services - No ADS also a good option.

**Comment by shwetaatgiphy** [comment]
Hey Everyone,

Hopefully suggestions by the community helped unblock all of you.
Please feel free to write in to developers@giphy.com if any of you still need help with this.

🙂
