### ISSUE TITLE
Is 'upload' via API removed or disabled?

### ISSUE THREAD

**Issue by donohoe** [Giphy/GiphyAPI#143]
I've seen old examples that refer to the ability to upload. From what I can tell these no longer work. So is it still possible to use the API to upload a GIF? And if so, is there documentation on how to do this?

**Comment by dfinkler** [comment]
Hi @donohoe it is still possible however we are in the midst of reworking how we handle permissions and api key assignments.

**Comment by dfinkler** [comment]
quick update on this - we are working with a 3rd party developer to address a bug in a piece of software we use to help manage our infrastructure. Once this bug is addressed we will re-release the documentation and support public access to the upload api

**Comment by freak4pc** [comment]
Very old, but still a pending question; doesn't seem the API documentation has any endpoint for upload at this point?

**Comment by Sixuan** [comment]
We're working on putting the upload docs back to our documentation which will also include info regarding how we will manage upload permission. Will keep you updated on this.

**Comment by Sixuan** [comment]
You should see the Upload docs now on https://developers.giphy.com/docs/
