### ISSUE TITLE
random endpoint missing a lot of data

### ISSUE THREAD

**Issue by mupchrch** [Giphy/GiphyAPI#145]
I'm finding the random endpoint json response doesn't contain the `images` object. Is that expected?

The search endpoint does return that object. So if this is expected, I'd have to hit the server twice. Once to get a random gif, and another time to hit the search endpoint with that gif ID to get the proper response that contains the `images` object.

Also noticing other data is missing in the `gif` object, but my use case is for the `images` object to be populated.

**Comment by dfinkler** [comment]
hi @mupchrch you are correct in your observation that the random endpoint JSON differs from the others in many ways.  We're working on a solution but for the moment you could make a second request for the GIF by ID to get the complete images representation.

**Comment by davidharrigan** [comment]
@dfinkler Is there an issue open for the proposed solution that I can follow? I would rather not make the second request if it's something that will be addressed in the near future. The documentation for the endpoint is also misleading.

**Comment by mdmccoy** [comment]
Well if there are no plans to fix the return object here, I guess it's too much to ask that the documentation be updated to reflect the different GIF object. :-/
