### ISSUE TITLE
Documentation for Upload API

### ISSUE THREAD

**Issue by pavitran** [Giphy/GiphyAPI#146]
I've just created an app on GIphy Dashboard, and got an API key. I've searched a lot but couldn't find any documentation on uploading GIFs to Giphy. Can anyone point me in the right direction.
Thanks in advance

**Comment by pavitran** [comment]
I tried the below with the current API key, but I'm getting `{"meta":{"status":401,"msg":"Unauthorized","error_code":"invalid_api_key","response_id":"59aa47cf65546543326d2cfc"}}`

curl -v -H 'Content-Type: multipart/form-data' -H 'Accept: application/json' -F "file=@giph.gif" http://upload.giphy.com/v1/gifs?api_key=api_key

**Comment by dfinkler** [comment]
HI @pavitran we're working on updating the developer documentation with updated Upload specs.  As soon as it's available we'll make an announcement - should be available soon!

**Comment by shwetachitlangia** [comment]
I got the same error. Please provide the documentation.
Why is the key addresses as invalid when it is actually valid.

**Comment by dfinkler** [comment]
@shwetachitlangia it's on its way!  We'll be sure to update all requesting tickets when it's live.

**Comment by davidseek** [comment]
news? :)

**Comment by dfinkler** [comment]
@davidseek we're very close to rereleasing the upload API and should have updates very soon!

**Comment by dfinkler** [comment]
quick update on this - we are working with a 3rd party developer to address a bug in a piece of software we use to help manage our infrastructure.  Once this bug is addressed we will re-release the documentation and support public access to the upload api

**Comment by davidseek** [comment]
Alright. Waiting for it. Our project basically waits to be able to upload the GIFs now :)

**Comment by DavidNV** [comment]
Hello @dfinkler Thank your for hard work. Could you gie heads up when the docs are released? Again, thank you.

**Comment by davidseek** [comment]
News?

**Comment by nickbullock** [comment]
Waiting for it :)

**Comment by dfinkler** [comment]
We'll be sure to update this thread as soon as we have news!

**Comment by alaslipknot** [comment]
Any update ? 
My app (mobile game) is still on "pending" and i can't find the Public Upload API key anywhere, thanks!

**Comment by xaphod** [comment]
Yo @dfinkler it's been some more months any update? I'd like to support publishing GIFs made by my app to Giphy.

**Comment by pladaria** [comment]
Any updates?

**Comment by Sixuan** [comment]
Hey, sorry for the late response. This is available now here https://developers.giphy.com/docs/, and look for "upload API: Upload Endpoint" section.

**Comment by hippogamesunity** [comment]
Hi! How should I use Upload API wit Unity? Can't make it work(((
![image](https://user-images.githubusercontent.com/7318172/43577153-c311e882-9653-11e8-8682-aa9d8dc59852.png)

**Comment by Sixuan** [comment]
With Unity, could you try appending the api_key in the post url and let me know if you still have issues? If so, send the error message again?

**Comment by erikmf12** [comment]
@hippogamesunity Did you ever figure out how to do this?

**Comment by hippogamesunity** [comment]
@erikmf12 Still not. I've received production key, but still unable to upload GIF. Have no response from support team.

**Comment by hippogamesunity** [comment]
@erikmf12
here is my working C# code

var form = new WWWForm();

form.AddField("api_key", apiKey);
form.AddField("username", "pixelstudio");
form.AddBinaryData("file", binary, fileName, "application/octet-stream");
form.AddField("tags", tags);

**Comment by erikmf12** [comment]
@hippogamesunity What type is your 'binary' variable? Is it a base64 encoded byte array?

**Comment by hippogamesunity** [comment]
It is byte array.

**Comment by LanXiaoPang613** [comment]
Hi, i have try your code, but couldn't working , if possible, can you show your full code. such as Downloader.Download("https://upload.giphy.com/v1/gifs?api_key=" + apiKey, form, www => ...

**Comment by hippogamesunity** [comment]
Oh, it is just a wrapper over Unity WWW download, refer to Unity docs.

**Comment by LanXiaoPang613** [comment]
Ok，i just want to know how the www=>...write, thx for your reply.

**Comment by hippogamesunity** [comment]
By the way, here is my asset with GIPHY upload example: https://www.assetstore.unity3d.com/#!/content/120039

**Comment by LanXiaoPang613** [comment]
Hi guys, can you tell me which class the downloader is ?

**Comment by hippogamesunity** [comment]
@LanXiaoPang613 https://docs.unity3d.com/ScriptReference/WWWForm.html

**Comment by LanXiaoPang613** [comment]
oh, thx, i have resolve it ,anyway, thank for your reply.

**Comment by hippogamesunity** [comment]
@LanXiaoPang613
- check "username"
- check api_key in two places
- you must have approved key (have to wait a few days in my case after approve)

**Comment by pierasg** [comment]
I see that some of you have gone through this successfully, still I want to share this quick solution I've found using NodeJS.

`const request = require('request');
const fs = require('fs');

var postData = {
	api_key: 'yourGiphyKeyGoesHere',
	file: {
		value:  fs.createReadStream('filename.gif'),
		options: {
			filename: 'filename.gif',
			contentType: 'image/gif'
		}
	},
	tags: 'tags,comma,separated',
	source_post_url: 'https://www.example.com/postId'
};

uploadToGiphy(postData).then((gifUrl) => {
	console.log('Gif posted to ' + gifUrl);
});

function uploadToGiphy(postData) {
	var options = {
		url: 'https://upload.giphy.com/v1/gifs?api_key=' + postData.api_key,
		formData: postData,
		json: true
	};
	console.log('Uploading via ' +  options.url);
	const p = new Promise((resolve, reject) => {
		request.post(options, function (e, resp, body) {
			if(e || resp.statusCode !== 200) console.log('giphy upload failed: ' + e);
			resolve('https://media.giphy.com/media/' + body.data.id + '/giphy.gif');
		});
	});
	return p;
}`

**Comment by mozebdi** [comment]
@pierasg Can I add this code as an example to the documentation in order to close this PR?

**Comment by anagaetan** [comment]
Not sure if anyone will see this message since this is an old thread, but I'm trying to do this and I have no idea if its working or not, and if it is, is there any way to see the uploaded gif? This is my code so far:

`    const UPLOAD_URL = "https://upload.giphy.com/v1/gifs?api_key=" + API_KEY;

    buttonupload.addEventListener('click', () => {

        let formData = new FormData();
        formData.append("file", blob, "myGif.gif");
        console.log(formData.get('file'))

        var xhr = new XMLHttpRequest();
        xhr.open("POST", UPLOAD_URL, true);
        xhr.withCredentials = true;
      
        xhr.setRequestHeader('Access-Control-Allow-Origin', '*');
        
        xhr.onreadystatechange = function () { 
            if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
                
                console.log('status 200')
            }            
        }
        try { 
            xhr.send(formData)
            console.log('Try worked.')
         }
        catch (e) {
            console.log('Try didnt work. Error: ' + e)
        };
    })

`

**Comment by shwetaatgiphy** [comment]
Hey Everyone,

Looks like we have a couple potential solutions in this thread. Hopefully these have helped the community.
Please feel free to write in to developers@giphy.com if any of you still need help with this.
