### ISSUE TITLE
Some gif requests return a 403: Access Denied response

### ISSUE THREAD

**Issue by kchunterdeluxe** [Giphy/GiphyAPI#147]
Hi guys,

I'm not certain this is the place to report this issue, but I am currently building out a menu-bar application that utilizes your API. I have a "favorites" section for storing favorited gifs, however, I've noticed that *some* gifs return a 403 forbidden response when using the URL to access the `downsized_still` version of the gif for display. Some gifs return 403, other gifs seem to work fine. 

One of the offending requests' urls is: https://media.giphy.com/media/GFLcKd6MXid2M/giphy-downsized_s.gif. What's even odder is I am able to view that link in my browser just fine.

### Image of the request and visual feedback
<img width="600" alt="testing" src="https://user-images.githubusercontent.com/1574487/30895761-7aa234a0-a309-11e7-9238-51a59b2cfd75.png">

I am storing the gif IDs and constructing urls based on them. Here is a sample of the code I'm using to construct those urls:

```js
normalizeGifs = () => {
    return this.state.gifIds.map(id => ({
      id,
      downsized: `https://media.giphy.com/media/${id}/giphy-downsized.gif`,
      downsizedStill: `https://media.giphy.com/media/${id}/giphy-downsized_s.gif`,
      original: `https://media.giphy.com/media/${id}/giphy.gif`,
    }));
  };
```

Any ideas why some gifs are forbidden while others seem to work?

**Comment by dfinkler** [comment]
hiya @kchunterdeluxe - sorry to hear you're having issues with the downsized rendition.  My best guess is that we may have a bug on the backend setting permissions for certain renditions but this does not explain why the browser always works :) - this is very odd.  I'm going to take this to our imaging team and I'll let you know what we find out.

I will keep this marked open as a bug for now until we get to the bottom of this!

**Comment by cyburgee** [comment]
hello, @kchunterdeluxe the urls for a given version don't always follow the same pattern. For that particular gif, the downsized_still is "https://media2.giphy.com/media/GFLcKd6MXid2M/giphy_s.gif"
You'll have better results if you use the urls returned by the API instead of hard-coding the gif id into URL patterns.
