### ISSUE TITLE
GIF object missing title property

### ISSUE THREAD

**Issue by pejalo** [Giphy/GiphyAPI#150]
The GIF JSON object returned from the server used to contain a "title" string property. Sometime over the last couple of days it seems to have disappeared from the server response and also from the documented schema definition. What gives?

I recently submitted an app using the Giphy API to a company that I was interviewing with. It relied on this title property and now no longer works. I also wanted to submit this app to the App Store. Introducing undocumented breaking changes doesn't instill much confidence in the API :(

**Comment by dfinkler** [comment]
hi @pejalo sorry about that - there was a regression error that we introduced with a recent release that took our the title attribute.  A fix for this regression error is now out and title property is back in the API responses now.
