### ISSUE TITLE
Search by channel

### ISSUE THREAD

**Issue by VictorIADev** [Giphy/GiphyAPI#151]
I'd like to know if it is possible to search by the channel through the API. For example get all gifs that were created by some user(publisher).  Thanks.

**Comment by dfinkler** [comment]
Hi @VictorIADev we are currently in the midst of putting together new API functionality that will let you search across user channels - stay tuned!  I'll keep this ticket open and notify you when we release the new features

**Comment by VictorIADev** [comment]
@dfinkler Thanks.

**Comment by Holyoke** [comment]
Perhaps it's a privacy issue, but I would love for the API to support gettings gifs by username or channel - I've made a bunch of content directly with my giphy account, and I'd like to call upon my content only for my app's purposes.

**Comment by shwetaatgiphy** [comment]
Hi @VictorIADev & @JasonEb 

GIPHY now supports searching via username through the [API](https://developers.giphy.com/docs/api/endpoint#search) as long the account is approved by GIPHY. 
Additionally we also extended support for searching user generated stickers recently. You can find more details on our [blog](https://giphy.medium.com/make-find-and-use-your-own-gif-stickers-with-giphy-username-search-6cad2d3ae380)

Hope this helps.
