### ISSUE TITLE
GIF views/popularity

### ISSUE THREAD

**Issue by skcary77** [Giphy/GiphyAPI#152]
On the website when you look at a GIF you can see the number of views it has. However, I can't find this information anywhere in the search endpoint response. Could this be added as a property of the GIF Object?

**Comment by dfinkler** [comment]
hi @skcary77 thanks for the great suggestion suggestion - I'll mark this ticket as an enhancement request now and forward it to the team building our analytics services.

**Comment by shwetaatgiphy** [comment]
Hey @skcary77 

Could you please explain how this would be used in your applications so i can file a feature request? 
Thank you.

**Comment by shwetaatgiphy** [comment]
Hey @skcary77 

I'm closing this issue for now but if you could provide additional details in the future, I'd be happy to convey this feedback to relevant teams. 
Thank you
