### ISSUE TITLE
Random Endpoint returns incomplete GIF Object

### ISSUE THREAD

**Issue by kace** [Giphy/GiphyAPI#153]
The GIF object returned from the _random_ endpoint seems to be missing the 'embed_url' property. I have confirmed that this is the case using the API Explorer provided on [developers.giphy.com](developers.giphy.com) as well as in my own app. I have not bothered to check if there are more missing props.

Since the GIF object returned by the _get by ID_ endpoint does include the 'embed_url' prop, I am using it in a work-around where I request a random GIF then use the ID from this response to re-request the same GIF (this time with a 'embed_url' prop) from the _get by ID_ endpoint.

**Comment by dfinkler** [comment]
hi @kace - the random endpoint is inconsistent with the other endpoints in a variety of ways.  We're working on a solution to make everything more consistent in all API responses in hopes of reducing this sort of confusion. We'll keep this issue open for the time being and will notify you here when it has been released.

**Comment by shwetaatgiphy** [comment]
Hi @kace 

I'm closing this issue since its fixed now. Please feel free to reopen though if you have any further questions.

Thank you for bringing this to our attention. 🙏
