### ISSUE TITLE
Request outside US not completed

### ISSUE THREAD

**Issue by AlainGauthier** [Giphy/GiphyAPI#155]
Could it be that HTTPS requests issued outside the US, i.e. UK, China, works like between 0% to 50% of the time? 

I got feedback from UK users that they don't see GIF (rendered using IMG HTML tag with src is
 <images.downsized_medium.url>). After running some test with UK proxy I experienced that more than 50% of the time the images never got transferred. From the network tab of the dev console, 0 bits, and endless wait. The same images are 100% of the time transferred from America (Canada, US)

Do you have servers outside the US?
If not, do you suggest I replicate my self the images to a cloud instance and make my app fetch it from there so that far users (far from the US) are able to get the gifs?

**Comment by dfinkler** [comment]
Hi @AlainGauthier we use Fastly CDN to help us distribute our content globally.  We recently made some configuration changes to optimize distribution for Europe and Asia so you be seeing low latencies for UK users.  Would you mind visiting this site: 

[https://www.fastly-debug.com/](https://www.fastly-debug.com/)

This site will help generate a file to help us debug the routing issues you are experiencing with the CDN provider.

**Comment by AlainGauthier** [comment]
Hi @dfinkler, thanks, I will do some more test and will follow-up with Fastly using there debug link, thanks!
