### ISSUE TITLE
How do i get an upload Api key (private or public) ?

### ISSUE THREAD

**Issue by alaslipknot** [Giphy/GiphyAPI#157]
Hello,

I have never used the giphy API before and am kinda lost, we are about to finish the development of our mobile game, and we decided to use this asset from the unity asset store to record and upload gifs to giphy : 
[https://www.assetstore.unity3d.com/#!/content/90215?aid=1100l33US](https://www.assetstore.unity3d.com/#!/content/90215?aid=1100l33US)

After creating the App on the giphy dashboard, i got an App Key, but i can't find an upload key **anywhere**!

What am i missing please ?

Thanks

**Comment by pushkar13** [comment]
Hello,

I have the same problem in my app (simple gif camera).
Is there a key to upload gif anonymously? I mean, I would like my app users to be able to save and load their gifs on the giphy platform even if they are not registered directly ... ie API calls are only made with my giphy API key.
I do not know if it's possible.
I do not find anything in the documentation. Nothing on the upload. Nothing about the upload of a third part.

Thank you for your help.

**Comment by dfinkler** [comment]
@alaslipknot @pushkar13 we are working on getting the Upload API back online. Once it's back we're going to republish the upload documentation which we've since taken offline in the meanwhile! I'll keep this issue open and notify you guys when it's back.

**Comment by tazzkiller** [comment]
On POST request in the website i see a different api key and a session key, it's possible to use it on the api for upload or session key change lot's of time ?

**Comment by litemesa** [comment]
> Hello,
> 
> I have never used the giphy API before and am kinda lost, we are about to finish the development of our mobile game, and we decided to use this asset from the unity asset store to record and upload gifs to giphy :
> https://www.assetstore.unity3d.com/#!/content/90215?aid=1100l33US
> 
> After creating the App on the giphy dashboard, i got an App Key, but i can't find an upload key **anywhere**!
> 
> What am i missing please ?
> 
> Thanks

Same thing with the same plugin: I cannot upload gif because I don't have giphy upload api key. The Issue were opened 2 years ago, any progress on it?

**Comment by shwetaatgiphy** [comment]
Hi Everyone, 

You should be able to use a single GIPHY API key for GET and POST requests ( i.e search and upload). 
Please note - we do not allow anonymous content upload. All content uploaded will be associated with the API key's parent account. 

Definitely give it a try and let us know if you still run into issues.
Thank you
