### ISSUE TITLE
Can we assign an appstore link to the uploaded gif ?

### ISSUE THREAD

**Issue by alaslipknot** [Giphy/GiphyAPI#159]
Hello, 

Our game is almost done and we're using Giphy to let user upload and share gifs, the way we are currently doing it is that after uploading the gif, we ask the user if they want to open it in the browser, and from there they will have all the sharing options available from Giphy, we were wondering if there is anyway to have the shared gif include a link to the appstore ? 

We can easily solve this by instead of redirecting the user to the Giphy website, we can just copy the Gif URL and then do a native "text sharing" and add whatever text we want, but we would like to keep the "go to browser" (or giphy app) step.

Thanks

**Comment by dfinkler** [comment]
hi @alaslipknot can you elaborate more on your request?  Are you asking for the GIF detail page to include some link to your app in the app store if the attribute (eg "app_store_source") is present, it will be displayed as a link?

**Comment by shwetaatgiphy** [comment]
Hi @alaslipknot 

Just wanted to check in again and see if you're still looking for this functionality? If you could elaborate on your request that'd be super helpful. 
Thank you.

**Comment by shwetaatgiphy** [comment]
Hey @alaslipknot 
Please feel free to reopen this issue in the future if you still need help with this issue. 
:)
