### ISSUE TITLE
Can we rename the uploaded Gif ?

### ISSUE THREAD

**Issue by alaslipknot** [Giphy/GiphyAPI#160]
Hello, 

we are about to finish the development of our mobile game, and we decided to use this asset from the unity asset store to record and upload gifs to giphy :
[https://www.assetstore.unity3d.com/#!/content/90215?aid=1100l33US](https://www.assetstore.unity3d.com/#!/content/90215?aid=1100l33US)

the plugins allow for adding "Tags", and the 1st tag is apparently used as the Gif title, the problem is the tags are rearranged by popularity (correct ?), and so [this Gif](https://giphy.com/gifs/cute-fun-mobile-games-26CaNoRngcJPwuZgY) would have "_Cute_" as a title instead of "_Up Jump_" which is the game name.

Is there a workaround for this ?

thanks!

**Comment by dfinkler** [comment]
@alaslipknot at this time we dont offer the option to rename the GIF slug but we'll consider it as a feature moving forward.  We are reworking some of our upload ingest pipeline so I'll be sure this feature request is considered.
