### ISSUE TITLE
API inconsistency with API Explorer's get gifs by ids call

### ISSUE THREAD

**Issue by Holyoke** [Giphy/GiphyAPI#161]
Not sure if this is the most appropriate place to address this, but currently Giphy's [API Explorer ](https://developers.giphy.com/explorer/)doesn't match the current public api call syntax for getting Gifs by IDs.

![image](https://user-images.githubusercontent.com/6300995/34634990-787a8054-f23e-11e7-940e-bffdbe8ff1d4.png)

The highlighted text in the Request URL should read _ids_ instead. I verified the call works as expected with _ids_ as well. Note that I've manually edited out my api key in sake of privacy. 

Currently it returns a 200 response which makes the endpoint ambiguous in behavior, but this seems to be a standard response for query calls with undefined filters. 

It seems the issue is just in the front-end. Manually editing the text to _ids_ fulfills the expected response within Giphy API Explorer. 

![image](https://user-images.githubusercontent.com/6300995/34635070-604471ce-f23f-11e7-9f0c-a573999dccf4.png)

**Comment by dfinkler** [comment]
@Holyoke thanks for pointing this out.  I'm going to check in with the dev portal and have the inconsistencies addressed.  If you dont mind emailing me your address - we'd love to send you something in thanks from GIPHY Engineering!  My email is dan [at] giphy.com

**Comment by dfinkler** [comment]
@Holyoke looks like this bug has been fixed and the GIFs by IDs now has the correct query parameter "id" in place.
