### ISSUE TITLE
No query syntax docs

### ISSUE THREAD

**Issue by hipertracker** [Giphy/GiphyAPI#162]
I can't find any docs about the query syntax for /search. Do you support boolean operators? E.g. what query "foo bar baz" means? Is it interpreted as "foo OR bar OR baz"? Is it possible to find results based on the AND operator?

**Comment by dfinkler** [comment]
hi @hipertracker let me consult the search team and see if they can provide some additional guidance and documentation on query syntax.

**Comment by dfinkler** [comment]
@hipertracker GIPHY search will automatically look for exact matches to queries + AND match + OR match. With ranking determined in that order (exact, and, or). Explicit AND + OR boolean clauses in search queries are not supported. 

You can find more documentation on our API at our new developer site:

https://developers.giphy.com
