### ISSUE TITLE
Typo's in docs!

### ISSUE THREAD

**Issue by wahidshafique** [Giphy/GiphyAPI#163]
Some tiny little spelling errors I came across in the [docs](https://developers.giphy.com/docs/), highlighted in bold

## Getting Started with the GIPHY API
"...GIPHY's GIF **libary** is the largest in the world and includes"

### Request Parameters
q: string
Search query term or **prhase**.

### Request Parameters
q: string
Search query term or **prhase**.

## The Meta Object
"The Meta Object contains basic information regarding the request, whether it was successful, and the response given by the API. Click here to see a description of types of response codes the API might give you under different **cirumstances**."

**Comment by dfinkler** [comment]
@wahidshafique thanks for pointing these out! We'll address them right away! thank you! If you email me your address we'd love to send you something in thanks from GIPHY Engineering!
