### ISSUE TITLE
{"message":"Invalid authentication credentials"}

### ISSUE THREAD

**Issue by iHardikTrivedi** [Giphy/GiphyAPI#164]
I created GIPHY account & my **API Key** : **78zgQ0gTHPUM3J5jmmBX2noDH6wzL1g7**

I use GIPHY api in my iOS application & I run below api:

SEARCH : 

http://api.giphy.com/v1/gifs/search?q=love&api_key=78zgQ0gTHPUM3J5jmmBX2noDH6wzL1g7&limit=5

TRENDING : 

http://api.giphy.com/v1/gifs/trending?api_key=78zgQ0gTHPUM3J5jmmBX2noDH6wzL1g7&limit=5

BUT, it gives me below error on Browser:
**{"message":"Invalid authentication credentials"}**

Question : Do I missed something in calling api ?

**Comment by chunkingz** [comment]
I have just experienced this same issue, and am not sure why @iHardikTrivedi decided to close this issue without any comment as to why he's closing it and the issue still wasnt resolved by anyone

**Comment by Parth777777** [comment]
i have the same issue for my website
Please help me

**Comment by drakarisbelen** [comment]
Hi Guys! I'm having the same problem, I'm trying to google it, but it's supossed to be easy consumes that endpoing  =/
