### ISSUE TITLE
Autoplayable GIF link

### ISSUE THREAD

**Issue by iamtekeste** [Giphy/GiphyAPI#165]
Which one of the links to the GIF returned from the API autoplays on Twitter? I have tried most of them and none seem to autoplay. For example `images.fixed_width` would only work on Facebook but not Twitter.
I appreciate your help!

**Comment by iamtekeste** [comment]
This blog post says that sharing the link which seems to be similar to what is in `data.bitly_gif_url` should be autoplayable but this is not the case for me. Please refer to the screenshot on how that link renders on twitter.
<img width="591" alt="screen shot 2018-02-15 at 4 37 54 pm" src="https://user-images.githubusercontent.com/1515815/36282283-aab3c616-126e-11e8-95b9-924e6cd07e3f.png">

https://giphy.com/posts/how-to-share-giphy-gifs-on-twitter

**Comment by dfinkler** [comment]
@iamtekeste thanks for the report.  I'll check in with our content engineering team and see if they can chime in with an answer!

**Comment by cyburgee** [comment]
I'm unfamiliar with which links twitter will autoplay. However our own Twitter share button on the site takes advantage of the twitter upload API. You can find documentation here: https://developer.twitter.com/en/docs/media/upload-media/uploading-media/chunked-media-upload
Note that there is a 15MB limit for uploaded gifs so you can either sort through the media we offer in the "images" portion of our API response or you can just always choose "images->downsized_large->url" to get a link to a gif that is <= 8MB

**Comment by dfinkler** [comment]
We also have a document guide to the renditions we make available of each piece of content.  
https://developers.giphy.com/docs/#rendition-guide
