### ISSUE TITLE
API isn't responding

### ISSUE THREAD

**Issue by eggsywashere** [Giphy/GiphyAPI#166]
Title says everything; I was using your API with my Discord bot and it stopped & started to giving errors to console. Looks like API is dead for? Hmm... I don't know. Do I need another app? Is there a quota because it says in _nowhere_. Anyway, I tried generating new URL from Developers site and didn't worked.

http://api.giphy.com/v1/gifs/random?api_key=MY_KEY_OFC&tag=somethingWAShere

**Comment by DanielRLevine** [comment]
This is specific to the random endpoint.  See #167.

**Comment by Sixuan** [comment]
My apologies for the inconvenience, there’s a fix in progress, this issue should be resolved in an hour. We will update once it’s out.

**Comment by Sixuan** [comment]
It should be resolved now. Let us know if there’s anything. Thanks for using/supporting our API.

**Comment by dfinkler** [comment]
@DanielRLevine we had an issue with that endpoint but as @Sixuan reported the issue should be resolved.  Let us know if you continue to have any issues - marking this as closed for now.
