### ISSUE TITLE
Random API endpoint returns no data

### ISSUE THREAD

**Issue by z1c0** [Giphy/GiphyAPI#167]
I have been using the **random API endpoint**.
https://api.giphy.com/v1/gifs/random

Unfortunately it does not return data any more. Can easily be repoduced using https://developers.giphy.com/explorer/

Only occurs for public API, sticker API works btw.

**Comment by skabbit** [comment]
Got this when using /random endpoint.
Other works well.
![screen shot 2018-02-24 at 17 04 32](https://user-images.githubusercontent.com/362857/36631266-ee105c26-1985-11e8-8f24-402f271add16.png)

**Comment by KurozeroPB** [comment]
Same, making a get request to `https://api.giphy.com/v1/gifs/random` with my api key doesn't give the expected json data also tried to explicitly set fmt to json but it still returns html

**Comment by gerbilsinspace** [comment]
it looks like it's being redirected to tv.giphy.com, causing cors issues. 

Giphy have fixed this before in ticket 40.

https://github.com/Giphy/GiphyAPI/issues/40

**Comment by Sixuan** [comment]
My apologies for the inconvenience, there’s a fix in progress, this issue should be resolved in an hour. We will update once it’s out.

**Comment by Sixuan** [comment]
It should be resolved now. Let us know if there’s anything. Thanks for using/supporting our API.

**Comment by gerbilsinspace** [comment]
It's working now, thank you so much for your hard work!

**Comment by z1c0** [comment]
It's working again. Thank you for the quick fix!
