### ISSUE TITLE
black screen in giphy

### ISSUE THREAD

**Issue by evisored** [Giphy/GiphyAPI#168]
**Expected behavior**
If we open giphy in mobile browser then that appears only black screen

**Actual behavior**
when i want to open giphy only black look

**How to reproduce**
I want it to be opened via mobile browser

* Browser: Firefox
* Operating system: android 7.1.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=JhvUzZTQi_s&feature=youtu.be
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@visored/black-screen-in-giphy">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dfinkler** [comment]
thanks for the bug report @evisored  - going to follow up with the team that builds the mobile web app!

**Comment by evisored** [comment]
your welcome

**Comment by giannif** [comment]
This should be fixed. We are using the [browser history api](https://developer.mozilla.org/en-US/docs/Web/API/History_API), and Firefox has a limit on how much data you can put in the state. We removed some unnecessary data to meet the size requirements

**Comment by dfinkler** [comment]
Thanks @evisored for making us aware of this issue - closing it now as it is reported as fixed
