### ISSUE TITLE
Random Endpoint Returns Duplicate Gifs

### ISSUE THREAD

**Issue by megaoka** [Giphy/GiphyAPI#169]
I have a few examples if required, but lately when I have been using the random endpoint from the API, I keep getting the same gif in separate requests. It also seems to favor some gifs and will pull them as a result often.

Here is the call I am making (API key snipped):
```https://api.giphy.com/v1/gifs/random?api_key=SNIP&tag=&rating=PG-13```

Any help would be appreciated. 

Thanks!

Edit: Verbage

**Comment by megaoka** [comment]
Here are some examples. In case the second one, it hadn't been used in a couple days, maybe once or twice? And then returned the same gif again.

![gbex1](https://user-images.githubusercontent.com/5827722/38152626-8696120e-341d-11e8-83b5-a4546ffff8e9.PNG)
![gbex2](https://user-images.githubusercontent.com/5827722/38152627-86b012a8-341d-11e8-8a38-798a2ab09878.png)
![gbex3](https://user-images.githubusercontent.com/5827722/38152628-86c7e130-341d-11e8-9cbb-c9dd47bdff82.png)

**Comment by dfinkler** [comment]
thanks for the report that you arent seeing a great degree of randomness from that endpoint @megaoka  - we're looking into it

**Comment by megaoka** [comment]
Thanks so much! Please let me know if I can provide more data.

**Comment by dfinkler** [comment]
👍 we'll keep you posted once we have an update on this issue!

**Comment by megaoka** [comment]
I don't want to be too premature, but the endpoint has been a lot more random lately. Were you able to discover a fix?

**Comment by Sixuan** [comment]
This should be fixed now.

**Comment by ashraf-patel** [comment]
I am facing the same issue, I am getting the same Gif again and again.

**Comment by jimgreer** [comment]
I'm having the same problem
