### ISSUE TITLE
Upldoaded a GIF on Giphy without logging in, is it visible to everybody now?

### ISSUE THREAD

**Issue by Hisoka1000** [Giphy/GiphyAPI#170]
So i recently wanted to quickly create a gif, the first site i found was giphy and it went really smoothly
but then the gif i created suddenly was filed as "uploaded".
Now im really worried because it is a gif i made for private use, is that gif visible to everyone on the site now? because i really dont want it to go around...
i hope this is the right platform to ask that question, was also the first one i found on google :s

**Comment by shwetaatgiphy** [comment]
Hi @Hisoka1000 

We did not / do not add anonymous content to GIPHY search. 
Also today, users cannot upload content anonymously anymore. This way you have a whole suite of tools to upload and control access to your content. 

Hope this helps.
