### ISSUE TITLE
stickers/random always returns the same sticker

### ISSUE THREAD

**Issue by fab1o** [Giphy/GiphyAPI#171]
`http://api.giphy.com/v1/stickers/random`

It's my understanding that this endpoint should always return a different sticker, but this is not the case.

What should I do to get a random sticker?

**Comment by dfinkler** [comment]
hi @fab1o our API engineering team is aware of the problem and is working on a fix!

**Comment by Sixuan** [comment]
Sorry about the issue, this should be fixed now.
