### ISSUE TITLE
403 error does not return CORS headers

### ISSUE THREAD

**Issue by sergeykaikin** [Giphy/GiphyAPI#175]
Hi guys,

I am not sure if this is an issue or expected behaviour but CORS headers are not being returned with 403 (Unauthorized). This is the error you are getting if you've passed wrong/outdated API key. So because of this I am not able to properly handle the error.

With 400 error CORS headers are being returned though.

Cheers
<img width="866" alt="screen shot 2018-05-18 at 08 47 10" src="https://user-images.githubusercontent.com/8362026/40222867-e02187fa-5a78-11e8-87fb-7f2abe15ca87.png">

**Comment by shwetaatgiphy** [comment]
Hey @sergeykaikin 

We we made changes to CORS header management fairly recently. We now return the required header for 403 errors as well. Please give this a try again and feel free to open the issue if needed.
Hopefully those fixes help.

Thanks.
