### ISSUE TITLE
Uploading GIF by file requires source url anyways

### ISSUE THREAD

**Issue by ghost** [Giphy/GiphyAPI#176]
Hello.

I've been trying to send a file via the Upload endpoint, using Firebase Functions and Node.js, but the response always returns `{ meta: { status: 400, msg: 'Bad Request - No Source Url', response_id: 'RESPONSE_ID' } }`
 
Unless I've understood it wrong, the documentation says that the only fields I'm required to fill in are the _api_key_, the _username_ (once I hit production and if I'll do that in the first place) and **either** a path to a binary file on the local file system **or** the remote url to another, via the respective _file_ or _source_image_url_ fields

I'm using node's `http.request`, sending the following `application/x-www-form-urlencoded` object via POST
`const postData = querystring.stringify({
    'api_key': API_KEY,
    'file': fsPath,
    'tags': tags
});`
where fsPath is obtained by downloading a temporary copy of a Firebase Storage bucket asset, deleted as soon as the request completes, via the `fs` and `path` node modules.

This only happens with files. I've already tested uploading by _source_image_url_ and it works flawlessly, meaning I receive the ID back and can then use the JS API to obtain its variants back.
Before you ask, no, I cannot upload the gif somewhere and send the link; I could do that with Firebase Storage, but that would also increase the upkeep and billing costs linearly with the amount of images I'll upload, and I cannot afford that.

Is the API supposed to do that? or am I missing something?

EDIT: Worked around the issue by using different node modules and methods, as well as streaming the file's contents as an array of bytes with an `application/octet-stream` content-type.

**Comment by erikmf12** [comment]
Hi! I'm having the same problem. I'm trying to do this in .net and always got that same error. What encoding are you using to send the file contents?

**Comment by shwetaatgiphy** [comment]
Hey @ghost, 

Glad you were able to get it to work. 
@erikmf12 Hope that fix worked for you as well. If not please feel free to write in to developers@giphy.com and we can debug the issue further.

Thank you!
