### ISSUE TITLE
Favorites in Giphy for Slack 

### ISSUE THREAD

**Issue by Smorgan6** [Giphy/GiphyAPI#177]
I had an idea and my coworker directed me here to share. 

I think that in the Giphy app for slack it'd be cool if we could favorite gifs as we send them and use a command like "/giphy favorite" to be able to cycle through those favorites.

With the options the Giphy app already has (8 ball, echo, weather update) I don't think it would be too hard to create, but who knows.

Thanks for reading :)

**Comment by shwetaatgiphy** [comment]
Hey @Smorgan6 
That's such a great idea. I've let the relevant teams know. Stay tuned to our [GIPHY Blog](https://giphy.medium.com/) for updates. 
Thank you so much for writing in! 
:)
