### ISSUE TITLE
App and users

### ISSUE THREAD

**Issue by hippogamesunity** [Giphy/GiphyAPI#178]
I'm making Pixel Studio, a mobile app for pixel art and animation. Recently I've integrated GIPHY API to upload GIFs. I want to request the following features:
- add AUTHOR property when uploading GIFs
- add a feature to request GIFs by AUTHOR

Please note than my apps' users are not authorized on GIPHY, they upload GIFs to the apps' channel using its' production key.

**Comment by shwetaatgiphy** [comment]
Hey @hippogamesunity 

These are great suggestions and both have been conveyed to relevant teams at GIPHY. Thank you for writing in with these & definitely stay tuned to the [GIPHY blog](https://giphy.medium.com/) for updates on these.
