### ISSUE TITLE
Larger Gif Sizes

### ISSUE THREAD

**Issue by erikmf12** [Giphy/GiphyAPI#179]
Is Giphy's max gif size only 320x240? That's very small compared to others' gifs. Imgur has very large gifs available. Is there anyway to request a larger size from the requested gif? (Not necessarily a specific size, just larger for desktop)

**Comment by shwetaatgiphy** [comment]
Hi @erikmf12 

Thank you for writing in. GIPHY does not restrict the GIF dimensions. It is completely up to the content creator what sizes they prefer to upload. We make sure to provide the exact quality that the creator uploaded in the `original` rendition. Please take a look at other available renditions [here](https://developers.giphy.com/docs/optional-settings/#rendition-guide). 

Hope this helps. 
:)
