### ISSUE TITLE
Downsized information is sometimes incorrect, images are larger than claimed

### ISSUE THREAD

**Issue by whawker** [Giphy/GiphyAPI#181]
Hi there,

We have noticed some of the "downsized" images from the API are sometimes not sized correctly. The Giphy search API states the physical dimensions and filesize of the image, but in reality they are sometimes much larger. 

For instance, the gif with ID `mX3THb0thvX2PWdXbQ` from: https://api.giphy.com/v1/gifs/search?api_key=&[key]&q=notify&limit=25&offset=0&rating=G&lang=en returns

```
"downsized": {
  "url": "https://media1.giphy.com/media/mX3THb0thvX2PWdXbQ/giphy.gif",
  "width": "480",
  "height": "259",
  "size": "1788980"
}
```

However this image is actually 1168w x 630h pixels, and ~7MB instead of 1.2MB. Much more than the max 2MB claimed for downsized images in the documentation.

**Comment by shwetaatgiphy** [comment]
Hey @whawker 

So sorry you ran into this issue back in the day. I unfortunately can't "reproduce" this anymore. Currently this asset's dimensions match what the API is indicating. 
Hopefully the improvements we've made over time meant this doesn't occur anymore or as often. 🙂
