### ISSUE TITLE
Prevent downloading BIG size GIFs

### ISSUE THREAD

**Issue by yarekc** [Giphy/GiphyAPI#183]
Is there a way to put a filter on GIFs size before making a search ?
The goal is to prevent users to insert Gifs with size >10 megas for instance.

Regards

**Comment by shwetaatgiphy** [comment]
Hey @yarekc 

GIPHY provides multiple [renditions](https://developers.giphy.com/docs/optional-settings/#rendition-guide) for every GIF that is returned, including a couple downsized versions, all of which provide you with assets less than 10MB. This way users are not restricted on what they can search for but you have complete flexibility to decide what size GIF is provided to them on selection.

Hope this helps.
