### ISSUE TITLE
Five gifs with same tag but only one searchable

### ISSUE THREAD

**Issue by kankando** [Giphy/GiphyAPI#184]
Hell Giphy Team,

I have uploaded five gifs to my company account, and i can see all five on dashboard and all with the same tag which is my company name. But only one out of five is searchable. I can't figure out why, so i post here for help. tag i searched for is cointmr, which is my company name and here is my company's dashboard ( https://giphy.com/cointmr )

**Comment by shwetaatgiphy** [comment]
Hi @kankando 

I couldn't reproduce the issue. Seems like multiple GIFs are now searchable using the tag `cointmr`. 
Please feel free to reopen the issue if thats not the case for you.
Thank you.
