### ISSUE TITLE
/giphy #caption fails all the time

### ISSUE THREAD

**Issue by arahayrabedian** [Giphy/GiphyAPI#186]
Not sure if this is a retired easter egg/feature, but in slack the `#caption` system/syntax no longer works (and has been the case for a while, but not more than a few weeks)

trying `/giphy #caption "nonono" no` (which is almost guaranteed to actually have a result) consistently returns `Giphy could not match #caption "nonono" no`

Haven't tried the other `#options` to see if this is a systematic failure, but this one is a super useful one

**Comment by seanpquig** [comment]
Yes this was fixed yesterday @arahayrabedian!  Thanks for reporting.

**Comment by KevinCressyArup** [comment]
not working?
