### ISSUE TITLE
Search filters particular words

### ISSUE THREAD

**Issue by desrocchi** [Giphy/GiphyAPI#187]
I stepped on this issue by chance and by testing I found that some words are actually filtered out of the API search function.

These word seem to be cut out of the normal search because of potential hate speech, but others, like "pussy", generate hundreds of results on the site, zero in the API.

These words seem to be actually erased from the search (so if you search "pussy dog" you get the results for just "dog").

All the while words like "cock" or "vagina" are accepted without any problem, so it does not seem to be a problem of NSFW settings.

**Comment by shwetaatgiphy** [comment]
HI @desrocchi 

Thanks for writing in. 
You're right that `pussy` should not be blocked completely.
I just tried a search API call with `pussy` and seems like the term isn't blocked anymore.
