### ISSUE TITLE
API won't return any data

### ISSUE THREAD

**Issue by kubajznik** [Giphy/GiphyAPI#189]
Can't get any data, neither random API neither any other ...
Also tried https://developers.giphy.com/explorer/ but it doesn't work, I just get { } ...
Am I missing something?
![unbenannt](https://user-images.githubusercontent.com/35335130/51276776-fb847080-19d5-11e9-8bfd-c85e15017123.PNG)

**Comment by shwetaatgiphy** [comment]
Hey @kubajznik 

Please let us know if this is still an issue for you? 
If yes - please share your API key and I can look into it further

Thank you!

**Comment by kubajznik** [comment]
Hey, no thanks. I found another way.
