### ISSUE TITLE
CORS headers on gifs

### ISSUE THREAD

**Issue by fisch0920** [Giphy/GiphyAPI#19]
I'm using the Giphy API and it's working really well, with the exception that about 30% of the GIFs fail to load on account of missing CORS headers.  I'm using the GIFs in a canvas context, so I need all GIFs to contain proper CORS headers, and I'm not sure if it's intentional or not that some contain the headers whereas others don't, so I wanted to follow up here and ask what the expectation is.  If they don't all support CORS, then this should be an option when querying the API to restrict the set of returnable GIFs to those which support CORS.

I'm loading the GIFs via something akin to ```<img src="..." crossOrigin="anonymous" />```.

Danke.

**Comment by dfinkler** [comment]
we're working on globally enabling CORS on our media content - we'll be in touch and make a formal announcement once this is in place

**Comment by alexchung** [comment]
@fisch0920 can you give us an example of the gif that is giving you an invalid cors header?

**Comment by dfinkler** [comment]
@fisch0920 All our media content should be delivered with CORS headers in place.  If this is not the case please send us a request or GIF ID that doesnt conform to this so we can investigate further.  

I am closing this issue since we havent heard back for a few months.
