### ISSUE TITLE
CORS for 429 error

### ISSUE THREAD

**Issue by BFoucher** [Giphy/GiphyAPI#190]
When your api rate is exceeded, the api return a 429 error, that good but CORS header are missing so we can not see the rate limit error.

**Comment by Ilyes512** [comment]
Yup, CORS headers should be added. Surprised it's hasn't been added yet since this is already reported on 18 jan!

**Comment by shwetaatgiphy** [comment]
Hi @Ilyes512 , @BFoucher 

We made changes to CORS header management fairly recently. Please give this a try again & feel free to reopen the issue if needed.
