### ISSUE TITLE
Rate limit of giphy API

### ISSUE THREAD

**Issue by poojajadav3698** [Giphy/GiphyAPI#191]
I'm using giphy API for get GIF stickers but I'm kind of confusion with giphy API guide on rate limiting mention over here:

https://developers.giphy.com/docs/#response-codes

I will get 429(Response Code) when my API key rate limits exceed. I have to manage 429 HTTP status code. But I don't know, how many request I can in giphy API for demo mode and production mode?

Thank you

**Comment by joshuahaslam** [comment]
The [FAQ](https://developers.giphy.com/faq) should answer your questions:

Q: What's the rate-limit for a newly created key?
A: We allow all newly created keys to have a maximum of 42 search requests an hour, 1000 search requests a day and 10 upload requests a day. Need to make more requests? Need support on our side to help you launch your app into production? See the next question.

Q: I'm ready to move my app into production! How can I get an production API Key that doesn't have rate limits?
A: Once you're ready to use the Giphy API in production, click on the "Request a production key" link on the app dashboard. We'll ask you to provide a little bit more info about your app and, if it meets our criteria, we'll upgrade your app and work with you to make sure your GIPHY integration is rock-solid.

**Comment by shwetaatgiphy** [comment]
Thank you @joshuahaslam ! 
Hope that cleared up all the questions @poojajadav3698

**Comment by caleb15** [comment]
@joshuahaslam what is the rate limit for production keys?

**Comment by joshuahaslam** [comment]
> @joshuahaslam what is the rate limit for production keys?

I don't know for sure, as I only have a beta key myself, but the FAQ implies there isn't one:

Q: I applied for a production key and my app was rejected. What does that mean? Can I reapply?
A: If you were rejected, don't fret. We'll provide you feedback on why your app didn't qualify for a production key. Oftentimes, your app may not need to make **_unlimited requests_**, and will function just fine with a rate-limited beta key. Once any issues are addressed, your app can be resubmitted through the developer portal for reassessment.
