### ISSUE TITLE
The random endpoint returns results that do not match the tag requested

### ISSUE THREAD

**Issue by joshuahaslam** [Giphy/GiphyAPI#193]
I just queried [https://api.giphy.com/v1/gifs/random?api_key=[key]&tag=funny-animals&rating=PG-13](https://api.giphy.com/v1/gifs/random?api_key=[key]&tag=funny-animals&rating=PG-13) and the API returned https://giphy.com/gifs/funny-scared-TlqRQ1nowmHIs.

At time of writing, that GIF is tagged with the following:
#funny
#anime
#scared
#manga
#terrified
#gto
#onizuka
#great teacher onizuka

Total guess, but it seems that "funny-animals" matches "funny".  If so, I'd consider that a bug.  Please can you investigate?

**Comment by joshuahaslam** [comment]
It just returned https://giphy.com/gifs/workaholics-blake-anderson-henderson-T49D8eK25QTC0, whose current tags are:
#workaholics
#blake anderson
#blake henderson
#get weird
#fish bro

I don't think the "funny-animals" tag works at all on the API, even though https://giphy.com/explore/funny-animals does.

**Comment by shwetaatgiphy** [comment]
Hey @joshuahaslam 


Thank you for writing in. 
The random endpoint doesn’t match tags on the request and the GIF tags one-to-one. Rather the tags are processed by a service that returns a related random GIF. Hence you see the variation in results.   For eg: When I made this API call these were the responses on my first 3 attempts: https://giphy.com/gifs/love-funny-cute-QfmRynMcJiiHe
https://giphy.com/gifs/love-XgvonjEePKXzq
https://giphy.com/gifs/funny-animation-hQubnR0Fr0dUI

Hope this explains the random endpoint a bit better.
