### ISSUE TITLE
Unclear Documentation for GIPHY Custom APIs

### ISSUE THREAD

**Issue by sabriele** [Giphy/GiphyAPI#194]
Hi there, I was trying to search for a way to accomplish the autocomplete functionality that GIPHY search bars (on the website) have. Googling for instructions leads me to the [Custom APIs](https://developers.giphy.com/docs/#custom-apis) section in the documentation. However, there are no links or further documentation with regards to autocomplete or the other APIs mentioned under this section.

Is this section meant to highlight future APIs that are still in production, or am I missing some documentation somewhere? Would it be possible to explain a little further what Custom APIs do, and where I can find their demos?

Thank you!

**Comment by shwetaatgiphy** [comment]
Hi @sabriele 
Apologies for the frustration, but we also have great news about the Autocomplete API. 
We released it a couple months ago publicly. You can find documentation for it and some more new endpoints [here](https://developers.giphy.com/docs/api/endpoint#autocomplete). 
Hope that helps.
