### ISSUE TITLE
API randomly returning no data

### ISSUE THREAD

**Issue by matt-allan** [Giphy/GiphyAPI#197]
We have been noticing a lot of errors where requests to `v1/gifs/search` that should be returning data are returning 0 results.

I was debugging this locally with [httpie](https://httpie.org/) and I am able to reproduce the issue reliably.

I made this request which returned an empty response:

```
$ http 'https://api.giphy.com/v1/gifs/search?q=dogs&apiKey={REDACTED}&limit=2&rating=g&lang=en'      
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 90
Connection: keep-alive
Content-Length: 136
Content-Type: application/json
Date: Wed, 03 Jul 2019 22:13:33 GMT
Retry-After: 0
X-Cache-Hits: 0, 1
X-Cachiness-CDN-Content-If-Error-TTL: 86400.000
X-Cachiness-CDN-Content-Varnish-Grace-TTL: 86400.000
X-Cachiness-CDN-Content-While-Revalidate-TTL: 1200.000
X-Cachiness-Edge-Timeout: 21600.000
X-Cachiness-Origin-Respect: 30s
X-Cachiness-Rule-Name: giphy_api_search_long_ttl
X-Rule-Debug: 1
X-Served-By: cache-bwi5144-BWI, cache-atl6241-ATL
X-Timer: S1562192014.621278,VS0,VE1
cache-control: max-age=30

{
    "data": [],
    "meta": {
        "msg": "OK",
        "response_id": "",
        "status": 200
    }
}
```

I then made multiple requests which returned the exact same thing. However eventually it started returning data:

```
$ http 'https://api.giphy.com/v1/gifs/search?q=dogs&apiKey={REDACTED}&limit=2&rating=g&lang=en'
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Accept, x-requested-with, cache-control
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Age: 28
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 2052
Content-Type: application/json
Date: Wed, 03 Jul 2019 22:14:56 GMT
Vary: Accept-Encoding
X-Cache-Control: max-age=30
X-Cache-Hits: 0, 1
X-Cachiness-CDN-Content-If-Error-TTL: 86400.000
X-Cachiness-CDN-Content-Varnish-Grace-TTL: 86400.000
X-Cachiness-CDN-Content-While-Revalidate-TTL: 1200.000
X-Cachiness-Edge-Timeout: 30.000
X-Cachiness-Origin-Respect: 30s
X-Cachiness-Rule-Name: debug_rule_giphy_api_surrogate_ttl
X-RateLimit-Limit-day: 1050000000
X-RateLimit-Limit-hour: 43700000
X-RateLimit-Remaining-day: 1049999998
X-RateLimit-Remaining-hour: 43699999
X-Robots-Tag: noindex
X-Rule-Debug: 1
X-Served-By: cache-bwi5141-BWI, cache-fty21349-FTY
X-Timer: S1562192097.990323,VS0,VE1
cache-control: max-age=30

{
    "data": [
        {
            // first result....
        },
        {
            // second result...
    ],
    "meta": {
        "msg": "OK",
        "response_id": "5d1d28c433446961558e5588",
        "status": 200
    },
    "pagination": {
        "count": 2,
        "offset": 0,
        "total_count": 70590
    }
}
```

What is going on here? The `Retry-After` header makes it look like it might be because of rate limiting but the 200 OK response makes it look like it's not.

**Comment by Sixuan** [comment]
this should be fixed on production. Please let us know if you still see them.

**Comment by ZzZombo** [comment]
Still seems to happen. I make the following request: `https://api.giphy.com/v1/gifs/search?q=help&limit=24&offset=26016&api_key=<CLASSIFIED>&rating=PG`. Now it might be that the offset is too big? How do I know? The docs are not clear on how to use the `pagination` object. I assume you have to advance `offset` by how many images were returned, so to get the last page of results as I did in the request, I need to multiply `limit` by `total_count / limit + 1`. But I suppose it's not that, because even then the returned data shouldn't read this:

    {"data":[],"pagination":{"total_count":0,"count":0,"offset":0},"meta":{"status":200,"msg":"OK","response_id":"212af1b5b1b60f3e622db0974de70ea521c5e4e6"}}

See all `pagination` fields are set to 0, although my query does have results and starting pages are all OK to some limit I've not explored, so `total_count` shouldn't also be 0.

**Comment by maxired** [comment]
@Sixuan I am currenlty facing this issue, 

`curl https://api.giphy.com/v1/gifs/search\?q\=car\&api_key\=<API_KEY>`

returns me 
```
{
        "data": [],
        "meta": {
          "status": 200,
          "msg": "OK",
          "response_id": ""
        }
```

**Comment by CMLivingston** [comment]
I'm experiencing the same issue for the `car` query as well when using a similar request to maxired@ to fetch data from `/v1/stickers/search` endpoint. Any assistance from the GIPHY team would be greatly appreciated. Thanks in advance!

**Comment by shwetaatgiphy** [comment]
Hi Everyone,

What you're seeing when status = 200 and responseID is empty is what GIPHY calls a synthetic response and occurs intermittently in some uncommon situations. 
We definitely recommend handling this in the code as an error. 
Hope this helps
