### ISSUE TITLE
Gifs API returns status 200 but not returning data

### ISSUE THREAD

**Issue by jetzable** [Giphy/GiphyAPI#199]
![image](https://user-images.githubusercontent.com/38728281/63056165-173cf000-bead-11e9-8434-bfd869aca3f4.png)

**Comment by shwetaatgiphy** [comment]
Hi @jetzable 
Thanks for bringing this to our attention! Given this is an older issue I am unable to reproduce it at the moment.
Please let us know if you can still reproduce this with some other calls and we'll take a look into it!
Thank you 🙏
