### ISSUE TITLE
Duplicated GIFs in search endpoint

### ISSUE THREAD

**Issue by blvdmitry** [Giphy/GiphyAPI#200]
Hey, I've been testing Search endpoint using it for pagination and found out that I get duplicated gifs occasionally according to their ids. It's reproduced on each request so no random behavior there.

### How to reproduce

First request, limit 10, offset 20, data[8] has an id of `l4JyZDdtFx7EbAEzm`:
https://api.giphy.com/v1/gifs/search?api_key=CdRKiCMbTnt9CkZTZ0lGukSczk6iT4Z6&limit=10&offset=10&rating=G&lang=en&q=kit

Second request, limit 10, offset 30, data[0] has the same id:
https://api.giphy.com/v1/gifs/search?api_key=CdRKiCMbTnt9CkZTZ0lGukSczk6iT4Z6&limit=10&offset=20&rating=G&lang=en&q=kit

**Comment by shwetaatgiphy** [comment]
Hey @blvdmitry,

Thanks for bringing this to our attention! Given this is an older issue I am unable to reproduce it at the moment. 
Please let us know if you can still reproduce this with some other calls and we'll take a look into it! 
Thank you 🙏
