### ISSUE TITLE
Seeing 404s on text media-typed gifs on "get gif by id" endpoint.

### ISSUE THREAD

**Issue by smurphy** [Giphy/GiphyAPI#201]
It seems like text media-typed gifs are not loading via the "get gif by id" endpoint. 
For instance api.giphy.com/v1/gifs/Xg3q3X43kDSMuGcdPn?api_key=<key> is 404ing but I think it should be a valid GIF. I'm using the iOS SDK and none of the text gifs are loading.

**Comment by smurphy** [comment]
Get gifs by ids is working thankfully: api.giphy.com/v1/gifs?ids=Xg3q3X43kDSMuGcdPn&api_key={{key}}

**Comment by shwetaatgiphy** [comment]
Hey @smurphy 
Thanks for bringing this to our attention. It seems like both endpoints work for this now, so it's likely the issue was fixed somewhere along the way. 
Appreciate the note! :)
