### ISSUE TITLE
Random endpoint does not return rating

### ISSUE THREAD

**Issue by akedalat** [Giphy/GiphyAPI#202]
Hi Team Giphy,

Testing the API with Postman, I can't get any rating property when sending request on either Random Gifs or Stickers
on `api.giphy.com/v1/gifs/random` or Random Stickers on `api.giphy.com/v1/stickers/random`

<img width="1594" alt="Screenshot 2019-10-28 at 12 16 42" src="https://user-images.githubusercontent.com/32881481/67677779-d79a8600-f97c-11e9-808c-d99a0e3c9cc2.png">
`

**Comment by ethanlu** [comment]
Should be fixed now.
