### ISSUE TITLE
slack #weather command broken

### ISSUE THREAD

**Issue by tdinetta7** [Giphy/GiphyAPI#203]
doing `/giphy #weather 02110` gives me this:  
  
![Screenshot from 2019-11-13 08-19-51](https://user-images.githubusercontent.com/25331364/68767318-7b776900-05ee-11ea-8e7f-312aa3dadd90.png)

**Comment by dylankolson** [comment]
Still an issue

**Comment by Sixuan** [comment]
Hey sorry for the incident. We looked at this internally, this feature is no longer supported due to various reasons. It sucks, but we will update relevant docs to reflect that from our end.

**Comment by shwetaatgiphy** [comment]
Thanks for bringing this to our attention @tdinetta7. 👍 
We do not support this command on Slack anymore as mentioned above.
