### ISSUE TITLE
undocumented is_sticker parameter

### ISSUE THREAD

**Issue by arranlomas** [Giphy/GiphyAPI#204]
I have noticed an undocumented `is_sticker` parameter on `GifObject`. I was wondering what the status of this parameter is, is it deprecated or are the docs just not updated?

example request:
http://api.giphy.com/v1/gifs/search?q=ryan+gosling+sticker&api_key=<API_KEY>&limit=5

Thanks!

**Comment by Sixuan** [comment]
Right now it's just undocumented, it might or might not be deprecated in the future. 
However, I'm curious what's your usage of that param? If you're making request to /v1/gifs/search, you can trust all the gifs returned are is_sticker = false and we recommend not looking at that param in that case, thus you won't be worried about we deprecating this field in the future if it does happen.

**Comment by arranlomas** [comment]
Firstly, thanks for the response.

> I'm curious what's your usage of that param? If you're making request to /v1/gifs/search, you can trust all the gifs returned are is_sticker = false

That doesn't always seems to be the case. 

In the example I mentioned above with a request of http://api.giphy.com/v1/gifs/search?q=ryan+gosling+sticker&api_key=<API_KEY>&limit=5

The result will be 
```
{
   "data":[
      {
         "type":"gif",
         "id":"3ov9jKgMaZq8KxkgFy",
         "url":"https://giphy.com/stickers/ryan-gosling-sticker-3ov9jKgMaZq8KxkgFy",
         "slug":"ryan-gosling-sticker-3ov9jKgMaZq8KxkgFy",
         "bitly_gif_url":"https://gph.is/2ydosqH",
         "bitly_url":"https://gph.is/2ydosqH",
         "embed_url":"https://giphy.com/embed/3ov9jKgMaZq8KxkgFy",
         "username":"josh",
         "source":"",
         "title":"ryan gosling sticker by Josh Rigling",
         "rating":"pg",
         "content_url":"",
         "source_tld":"",
         "source_post_url":"",
         "is_sticker":1,
         "import_datetime":"2017-10-12 23:36:18",
         "trending_datetime":"0000-00-00 00:00:00",
         "images":{
            ...
         },
         "user":{
            "avatar_url":"https://media0.giphy.com/avatars/josh/Aj2EVHqhwA3c.gif",
            "banner_image":"https://media0.giphy.com/headers/josh/cOAoJGVTLK9L.gif",
            "banner_url":"https://media0.giphy.com/headers/josh/cOAoJGVTLK9L.gif",
            "profile_url":"https://giphy.com/josh/",
            "username":"josh",
            "display_name":"Josh Rigling",
            "is_verified":true
         },
         "analytics":{
            "onload":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=6e4a8ca79be1453d4e5eeab830ffb804bf9acc62&event_type=GIF_SEARCH&gif_id=3ov9jKgMaZq8KxkgFy&action_type=SEEN"
            },
            "onclick":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=6e4a8ca79be1453d4e5eeab830ffb804bf9acc62&event_type=GIF_SEARCH&gif_id=3ov9jKgMaZq8KxkgFy&action_type=CLICK"
            },
            "onsent":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=6e4a8ca79be1453d4e5eeab830ffb804bf9acc62&event_type=GIF_SEARCH&gif_id=3ov9jKgMaZq8KxkgFy&action_type=SENT"
            }
         }
      }
   ],
   "pagination":{
      "total_count":48,
      "count":1,
      "offset":0
   },
   "meta":{
      "status":200,
      "msg":"OK",
      "response_id":"6e4a8ca79be1453d4e5eeab830ffb804bf9acc62"
   }
}
```

Notice `"is_sticker":1,`

Now if I make the same request with `ryan gosling` instead of `ryan gosling sticker` eg: http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=<API_KEY>&limit=1 

The result is: 
```
{
   "data":[
      {
         "type":"gif",
         "id":"rwNpHtaMGnStW",
         "url":"https://giphy.com/gifs/ryan-gosling-crazy-stupid-love-more-like-500k-wtf-rwNpHtaMGnStW",
         "slug":"ryan-gosling-crazy-stupid-love-more-like-500k-wtf-rwNpHtaMGnStW",
         "bitly_gif_url":"https://gph.is/1qcYHb5",
         "bitly_url":"https://gph.is/1qcYHb5",
         "embed_url":"https://giphy.com/embed/rwNpHtaMGnStW",
         "username":"",
         "source":"https://c-mines.tumblr.com/post/55390116615",
         "title":"ryan gosling GIF",
         "rating":"g",
         "content_url":"",
         "source_tld":"c-mines.tumblr.com",
         "source_post_url":"https://c-mines.tumblr.com/post/55390116615",
         "is_sticker":0,
         "import_datetime":"2013-07-14 03:05:00",
         "trending_datetime":"2019-11-12 19:13:56",
         "images":{
            ...
         },
         "analytics":{
            "onload":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=543fd531fdc5c54ccf24e3556db80dbccc61d3e1&event_type=GIF_SEARCH&gif_id=rwNpHtaMGnStW&action_type=SEEN"
            },
            "onclick":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=543fd531fdc5c54ccf24e3556db80dbccc61d3e1&event_type=GIF_SEARCH&gif_id=rwNpHtaMGnStW&action_type=CLICK"
            },
            "onsent":{
               "url":"https://giphy-analytics.giphy.com/simple_analytics?response_id=543fd531fdc5c54ccf24e3556db80dbccc61d3e1&event_type=GIF_SEARCH&gif_id=rwNpHtaMGnStW&action_type=SENT"
            }
         }
      }
   ],
   "pagination":{
      "total_count":2469,
      "count":1,
      "offset":0
   },
   "meta":{
      "status":200,
      "msg":"OK",
      "response_id":"543fd531fdc5c54ccf24e3556db80dbccc61d3e1"
   }
}
```

Notice `"is_sticker":0,`


Therefore searching with /v1/gifs/search doesn't necessarily mean `is_sticker` is always false. This means there may be results which contain transparency but there is no documented way to know they should be treated as a sticker.

Hopefully this clears up the questions around use case as well because we allow users to search for terms that include the word sticker.

**Comment by Sixuan** [comment]
I see thanks for explanation. That makes a lot of sense now. There's hidden usage when the query string contains "sticker" in it, which forces it look up the sticker library. 

Is it the end user who puts "sticker" as part of the query string or designed by the app? If it's the latter, are you open to use /v1/stickers/search endpoint for sticker usage purpose? Let me know if that's not the case and I'm happy to assist further.

**Comment by arranlomas** [comment]
> Is it the end user who puts "sticker" as part of the query string

Yes, it's the user.

**Comment by Sixuan** [comment]
Basically, then the search results will show the "sticker" type only (animated gif with transparent background). The is_sticker field indicates that currently.

**Comment by arranlomas** [comment]
Understood. It seems that leaves us with 2 options:
1. Use the undocumented `is_sticker` property.
2. Check the query to see if it contains the word `sticker`, if so assume all results will be stickers.

I have some concerns with both approaches:

If `is_sticker` is undocumented it could be removed/changed without warning.

Does checking the query work for other locales, eg, if a Spanish users uses the Spanish word for "sticker" will it still contain sticker results? 

Approach 2 also assumes that all results from a query containing the word "sticker" will actually be stickers and not a mix of results.

Approach 2 also depends on some undocumented behaviour which could change.

From my perspective, the ideal solution would be for `is_sticker` or the fact that a query contain "sticker" will only return sticker result to be documented and officially supported .


Thanks again 🎉

**Comment by Sixuan** [comment]
Feel free to use is_sticker property for now. 
I will a task on our side to update docs.
