### ISSUE TITLE
link to actual gif

### ISSUE THREAD

**Issue by kickbk** [Giphy/GiphyAPI#206]
I tried looking for a direct link to the actual gif image file and I cannot find it in the response. Our API needs the image URL to share on Facebook, but when we share one of the formats you provide, a static image is displayed.

Say I want to share on Facebook, via the API, the following gif:
![Screen Shot 2020-01-27 at 10 35 08 AM](https://user-images.githubusercontent.com/31323376/73202859-cfbfbe80-40f0-11ea-98d9-2b584d4cfb12.png)

Then I assumed I will share the following "original url": "https://media3.giphy.com/media/iG9XXNCR7lmM8mJTK7/giphy.gif?cid=e3b0c442c270bad8c7a7a970d347649b9259d3661d29b5f1&rid=giphy.gif"

However, if you visit this link, it's not actually a gif. It's HTML. The only thing I find there which acts as a gif is a link to https://i.giphy.com/media/iG9XXNCR7lmM8mJTK7/giphy.webp but even that is not a gif file.

I am a little confused. Is there a simple way to get a link to an actual gif image without all the HTML so we can share on Facebook via API?

**Comment by shwetaatgiphy** [comment]
Hi @kickbk ,

All of the URLs included within the image object will retrieve a suitable asset if accessed programmatically. If the `accept` header begins with `text/html` they are redirected to the web’s media landing page i.e you get the HTML response. 

Hope this helps.
