### ISSUE TITLE
Upload API - HTTP 423 Error

### ISSUE THREAD

**Issue by buyukim** [Giphy/GiphyAPI#207]
I keep getting HTTP 423 LOCKED errors when I try to use your upload API for my development application.  The only way I get anything different is if I use an incorrect api_key, then I get the expected 403.  I also tried to move the api_key into the body and both in query string and body, but I still get this undocumented 423 error.  Can you tell me if the upload API is supposed to be functional or if there are known issues?   

Here is a sample curl request:
curl -v -X POST "https://upload.giphy.com/v1/gifs?api_key=xxxxx" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"source_image_url\": \"https://images.squarespace-cdn.com/content/v1/5a52d1f2edaed8620f2aa1b5/1516380290302-NG05QGZYYOSLNIL8WLO7/ke17ZwdGBToddI8pDm48kATsp3JsZdmbPTNem4KYYE5Zw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIoNoOd3eUTp9p0QLYabKGbytQWpvtnq4ZfRnpAM3elUY/iwannagobed.gif?format=1500w\", \"tags\": \"sleepy\", \"source_post_url\": \"https://www.carlymonardo.com/animated-gifs\"}"

response:
...
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ffde6003c00)
> POST /v1/gifs?api_key=xxxxx HTTP/2
> Host: upload.giphy.com
> User-Agent: curl/7.64.1
> accept: application/json
> Content-Type: application/json
> Content-Length: 1
>
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 423
< content-type: text/plain; charset=UTF-8
< server: akka-http/10.1.8
< x-kong-upstream-latency: 2
< x-kong-proxy-latency: 5
< via: kong/0.34-1-enterprise-edition
< accept-ranges: bytes
< via: 1.1 varnish
< accept-ranges: bytes
< date: Mon, 10 Feb 2020 04:33:24 GMT
< via: 1.1 varnish
< x-served-by: cache-bwi5148-BWI, cache-lax8630-LAX
< x-cache: MISS, MISS
< x-cache-hits: 0, 0
< x-timer: S1581309205.886493,VS0,VE107
<
* Connection #0 to host upload.giphy.com left intact
The resource that is being accessed is locked.* Closing connection 0

**Comment by shwetaatgiphy** [comment]
Hey @buyukim 

I just tried this again and didnt run into any issues. Are you still running into this error while uploading?
For reference, this is the code I used: 

`curl -X POST \
  'http://upload.giphy.com/v1/gifs?api_key=YOUR_API_KEY' \
  -H 'content-type: multipart/form-data' \
  -F source_image_url=GIF_URL\
  -F tags=tag1,tag2`
