### ISSUE TITLE
How to fetch a random GIF with multiple tags?

### ISSUE THREAD

**Issue by zinfulness** [Giphy/GiphyAPI#210]
`tag` is a string, so can you only fetch a random GIF with a single tag, despite the fact that GIFs on Giphys can have multiple tags?

**Comment by shwetaatgiphy** [comment]
Hey @zinfulness 
You can pass multiple tags in the field by adding a space in between and http encoding the string.
For eg:
`https://api.giphy.com/v1/gifs/random?api_key=YOUR_API_KEY&tag=cat%20tuna%20fish`

Hope this helps.
