### ISSUE TITLE
returns wrong data if offset greaterAndEqual than 5000

### ISSUE THREAD

**Issue by yaolangEdmodo** [Giphy/GiphyAPI#211]

**Comment by yaolangEdmodo** [comment]
the data will always be like below after offset is greater than 5000                                                                  {
    "data": [],
    "pagination": {
        "total_count": 0,
        "count": 0,
        "offset": 0
    },
    "meta": {
        "status": 200,
        "msg": "OK",
        "response_id": "2ca1417aa35737581d956c1cf070c908a114ccf8"
    }
}

**Comment by shwetaatgiphy** [comment]
Hey @yaolangEdmodo 
Our API allows offset values between 0 - 4999. 
I will create a ticket to add this information to the Developer Docs.

Hope this helps

**Comment by yaolangEdmodo** [comment]
@shwetaatgiphy thanks and it must be helpful
