### ISSUE TITLE
get app random key

### ISSUE THREAD

**Issue by gjc2609** [Giphy/GiphyAPI#218]
we are using 
**GiphyCoreUI.configure(context = yourContext, apiKey = "your_api_key", verificationMode = true)** this function to generate App random id with **library 1.2.8.**

Giving error **unresolved reference** for GiphyCoreUI.

Please provide solution for the same

**Comment by shwetaatgiphy** [comment]
Hey @gjc2609,

Thank you for pointing out this issue, we are fixing this in our documentation soon. In the meantime, please use **Giphy.configure(context = yourContext, apiKey = "your_api_key", verificationMode = true)** instead, that should work.

If there are any other issues/ questions around the SDK please feel free to write into developers@giphy.com or open an issue in the  respective repositories ([iOS](https://github.com/Giphy/giphy-ios-sdk-ui-example), [Android](https://github.com/Giphy/giphy-android-sdk-ui-example), [Web](https://github.com/Giphy/giphy-js/issues))
