### ISSUE TITLE
Missing Callbacks "onGifsFetched" and "onGifsFetchError" in web SDK

### ISSUE THREAD

**Issue by kmschott** [Giphy/GiphyAPI#219]
The callbacks `onGifsFetched` and `onGifsFetchError` for the web SDK in the js-components especially in the `renderGrid` function are optional and not called if the `fetchGifs` function does not return anything.

This makes it currently impossible for me to check and display a hint, if the query does not return any results.

I use Vue.js instead of React and therefore the native web components. I use it like this:

```
const fetchGifs = new GiphyFetch(apiKey).search(query, { ... })

renderCarousel({
    fetchGifs,
    onGifsFetched: (gifs) => {
        ...
    },
    onGifClick: (gif, event) => {
        ...
    },
    ...
})
```

* "@giphy/js-components": "^3.0.5"
* "@giphy/js-fetch-api": "^1.5.9"

**Comment by shwetaatgiphy** [comment]
Hi @kmschott 
This looks to be an issue with out Web SDK. Please go ahead and create this issue in [that repository](https://github.com/Giphy/giphy-js/issues) so the right team can help out. 
Thank you for using our SDKs
