### ISSUE TITLE
'apiKey' parameter no longer supported by search endpoint

### ISSUE THREAD

**Issue by SaraFK** [Giphy/GiphyAPI#221]
As of a few days ago the search endpoint no longer supports use of 'apiKey', it works with api_key however. I believe the parameter name was updated at some point but the search endpoint is no longer backwards compatible. Trending endpoint still works with both apiKey and api_key;

search:
**Does not work** - https://api.giphy.com/v1/gifs/search?apiKey={REDACTED}&q=hello&limit=25&offset=0&rating=G&lang=en
**Works** - https://api.giphy.com/v1/gifs/search?api_key={REDACTED}&q=hello&limit=25&offset=0&rating=G&lang=en
trending:
**Works** - https://api.giphy.com/v1/gifs/trending?apiKey={REDACTED}
**Works** - https://api.giphy.com/v1/gifs/trending?api_key={REDACTED}

**Comment by Sixuan** [comment]
Sorry for the inconvenience, please use api_key param as we documented [on our developers portal](https://developers.giphy.com/docs/api/endpoint#search).

**Comment by SaraFK** [comment]
Thanks! yes we've started using api_key instead.

**Comment by Sixuan** [comment]
sweet. thanks for the response.
