### ISSUE TITLE
Bugs in loading videos on GiphyGridView

### ISSUE THREAD

**Issue by amitkle** [Giphy/GiphyAPI#222]
Hello,
I found two bugs using the GiphyGridView on "one+ 8 pro" device.
The GiphyGridView works great on other devices.
I've attached videos.
[giphy_videos.zip](https://github.com/Giphy/GiphyAPI/files/4995172/giphy_videos.zip)

**Comment by shwetaatgiphy** [comment]
Hi @amitkle 
This seems like an issue with one of our SDKs. 
Please create an issue in the the relevant repository ([iOS](https://github.com/Giphy/giphy-ios-sdk-ui-example), [Android](https://github.com/Giphy/giphy-android-sdk-ui-example/issues), [Web](https://github.com/Giphy/giphy-js/issues)) so the appropriate team can look into it. 
Thank you!
