### ISSUE TITLE
Incorrect response on Autocomplete API

### ISSUE THREAD

**Issue by SmyzerT** [Giphy/GiphyAPI#223]
API: https://developers.giphy.com/docs/api/endpoint#autocomplete

The data property of the response should contain Term Object[]
Some queries like `http://api.giphy.com/v1/gifs/search/tags?q=q` produce the incorrect responses, see attachments below

![2020-08-03_18-27](https://user-images.githubusercontent.com/9142919/89200233-61384d80-d5b8-11ea-999a-a98b1538a708.png)

![2020-08-03_18-26](https://user-images.githubusercontent.com/9142919/89200243-64cbd480-d5b8-11ea-8517-2116c522f3ce.png)

![2020-08-03_18-28](https://user-images.githubusercontent.com/9142919/89200254-67c6c500-d5b8-11ea-832b-b28e40a73a36.png)

**Comment by ethanlu** [comment]
@SmyzerT We identified the cause and have deployed a fix for this. The response should be formatted correctly now. Thanks for reporting the issue!
