### ISSUE TITLE
Incorrect documentation for Category Object

### ISSUE THREAD

**Issue by henrikac** [Giphy/GiphyAPI#234]
The documentation for [Category Object](https://developers.giphy.com/docs/api/schema/#category-object) states that `subcategories` is a `Subcategory Object` but it is actually a `Subcategory Object[]`.

**Comment by shwetaatgiphy** [comment]
Hey @henrikac 
Great catch! I've created a ticket for this to be fixed. 
Thank you!

**Comment by henrikac** [comment]
You're welcome :-)

**Comment by shwetaatgiphy** [comment]
Closing this issue since the fix is now live! thanks once again @henrikac
