### ISSUE TITLE
API search responses returning duplicate items

### ISSUE THREAD

**Issue by lukeredpath** [Giphy/GiphyAPI#235]
Our app currently makes use of the search and trending API endpoints and we display these in a `UICollectionView` within our iOS app. Since the 26th May, we've started seeing crashes in our app relating to the items in this collection view (representing the GIPHY search result items) having duplicate IDs.

Nothing has changed in our code and this affects old and new versions of our app - we have verified the cause of the issue and will be able to release a fix for this by explicitly de-duping the results however this doesn't help users on old versions of our app. The only thing I can think that has caused this to start happening is that the search API has started returning items with duplicate IDs since this date.

Has something changed at your end that could have caused this?

**Comment by Bruceeeeeee** [comment]
I also got the same problem, i set the offset correctly, but still receive duplicates.

**Comment by lukeredpath** [comment]
We solved this problem by using a `Set` instead of an `Array` for local storage of search results, ensuring we didn't have any duplicate items in our collection view.

**Comment by shwetaatgiphy** [comment]
Hi Everyone,
I have an update here. 

Due to certain changes in how the trending feed is populated this is expected behavior at the moment - On some occasions you will receive content with the same ID in a single response. 
This is not due to any issues with pagination. 

@lukeredpath Thank you for posting your solution here. Hopefully this helps other developers too. 🙏

**Comment by navrkald** [comment]
It's a bug in GH Search api: https://github.com/orgs/community/discussions/24361#discussioncomment-8212278 hope they might fix if finally after many years...

**Comment by lukeredpath** [comment]
@navrkald I'm not sure why you've replied to this issue - this issue relates to the GIPHY iOS SDK and has nothing to do with the Github search API.

**Comment by navrkald** [comment]
Thanks @lukeredpath , sorry my bad I have deleted original comment.
