### ISSUE TITLE
I also got the same problem, i set the offset correctly, but still receive duplicates.

### ISSUE THREAD

**Issue by karinna77** [Giphy/GiphyAPI#239]
I also got the same problem, i set the offset correctly, but still receive duplicates.

_Originally posted by @Bruceeeeeee in https://github.com/Giphy/GiphyAPI/issues/235#issuecomment-886350673_

**Comment by shwetaatgiphy** [comment]
Hi @karinna77 
Please see this comment - https://github.com/Giphy/GiphyAPI/issues/235#issuecomment-1074083911
Hope it helps 🙏
