### ISSUE TITLE
public beta key doen't seem to work

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [Giphy/GiphyAPI#27]
The public beta key given doen't seem to work..If i open this link http://api.giphy.com/v1/gifs/search?q=funny+cat&api_key=dc6zaTOxFJmzC   it shows {"meta":{"status":403,"msg":"Forbidden"}}..thanks for  such nice docs..plzz help me regarding public beta key

**Comment by phrmsilva** [comment]
Hey,
What was the fix for this?

**Comment by namslam** [comment]
@phrmsilva hmm weird! looks like it's working for us. Please note that the beta key is limited to ~1000 requests per IP per day. Have you exceeded the limit?

**Comment by austinkelleher** [comment]
Works for me too.

**Comment by phrmsilva** [comment]
Not exceeding the limit, no.

I guess it was on my end, I wasn't being able to make a get request through curl but other applications seem fine.

Thanks for the attention, though!

**Comment by namslam** [comment]
@phrmsilva no problem! let us know if you need anything else
