### ISSUE TITLE
Trending Endpoint return duplicates

### ISSUE THREAD

**Issue by mradzinski** [Giphy/GiphyAPI#29]
The trending endpoint return duplicates if you specify an offset.

I'm using the following endpoints:

    http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&limit=15&offset=0
    http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&limit=15&offset=1
    http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&limit=15&offset=2

offset 2 returns almost (not all) the same GIFs that offset 0, even in the same order.

**Comment by mradzinski** [comment]
Btw, you are also missing the Offset parameter documentation for the Trending endpoint.

**Comment by namslam** [comment]
hey mradzinski,

thanks for letting us know! we're running some tests now to see what's going on. once resolved, we'll also make a note to include the parameter documentation in the next API release. 

-nam

**Comment by ex3ndr** [comment]
Any updates?

**Comment by namslam** [comment]
Hey @ex3ndr,

This issue should be resolved. Are you still seeing dupes? If so can you send me an example API request you're making so I can check it?
