### ISSUE TITLE
Returning tags from search and by ID

### ISSUE THREAD

**Issue by silentorb** [Giphy/GiphyAPI#30]
Based on both the API docs and my own experimentation, some endpoints such as the search (v1/gifs/search) and "by ID" endpoints do not seem to be returning tags, but some of the other endpoints (such as v1/gifs/random) do return tags.  Why is this and is there a way to get tags from any endpoint?

I'm using the public API key in case that affects things.  I saw in another issue that tag results are limited for the public key (though it didn't say no tags would be returned.)

**Comment by mradzinski** [comment]
+1, only the `random` endpoint return tags, which is quite weird taking into consideration the endpoint has a tags parameter anyway.

**Comment by namslam** [comment]
hey silentorb, mradzinski,

tags via search and ID are currently reserved for private access only - we're looking to offer it as a public parameter soon, i'll keep you guys posted once we're ready. thanks!

-nam

**Comment by sergigracia** [comment]
+1 PLEASE
