### ISSUE TITLE
Search total_count wrong value

### ISSUE THREAD

**Issue by mradzinski** [Giphy/GiphyAPI#31]
Try the following:

***

http://api.giphy.com/v1/gifs/search?q=monkey+gun&limit=25&offset=1&api_key=dc6zaTOxFJmzC
returns: `"pagination":{"total_count":8,"count":7,"offset":"1"}}`

http://api.giphy.com/v1/gifs/search?q=monkey+gun&limit=25&offset=2&api_key=dc6zaTOxFJmzC
returns: `"pagination":{"total_count":8,"count":6,"offset":"2"}}`

***

How's possible that offset 1 returned 7 gifs while total_count equalled 8 and offset 2 returned 6 more gifs and total_count remained 8? I don't know, but 7 + 6 != 8...

So, or total_count value is totally wrong or the endpoint is returning an amazing number of duplicates. This happens for offset 3, 4, 5 and so on.

**Comment by namslam** [comment]
hey @mradzinski,

thanks for sharing this! will relay this to the team and mark it as something to look into.

**Comment by katebell483** [comment]
hi @mradzinski,

I think there may be some confusion over what "count" and "total_count" mean in our system. "count" indicates the total gifs returned per request, while "total_count" refers to the total number of gifs we have in our system. In the example above, by indicating an offset of 1 the number of gifs returned to you was one less than the total number we have in our system, which is 8. So 8 - the offset of 1, leads to a response of 7 gifs. An offset of 2, would leave only 6 gifs left to return. Generally people use these two numbers for accurate paging.

If you search for a more prevalent tag you would see total count and count stay the same despite offset for the majority of requests (ie regardless of declared offset, there are still 25 cat gifs to return):

http://api.giphy.com/v1/gifs/search?q=cat&limit=25&offset=1&offset=1&api_key=dc6zaTOxFJmzC
http://api.giphy.com/v1/gifs/search?q=cat&limit=25&offset=2&offset=1&api_key=dc6zaTOxFJmzC

That is, until you reach the end of our cat collection:
http://api.giphy.com/v1/gifs/search?q=cat&limit=25&offset=1&offset=26024&api_key=dc6zaTOxFJmzC

Does that make sense? Happy to answer any more questions you might have!

Best,

Kate
