### ISSUE TITLE
Pagination offset sometimes returned as int, sometimes as string when searching

### ISSUE THREAD

**Issue by paddycarey** [Giphy/GiphyAPI#35]
When an offset parameter is passed to the search API it is returned in the results as a string instead of an int.

You can see this behaviour at the following URLs:

(offset returned as string within "pagination" object)
http://api.giphy.com/v1/gifs/search?q=tom+hiddleston&api_key=dc6zaTOxFJmzC&limit=20&offset=100&rating=g

(offset returned as int within "pagination" object)
http://api.giphy.com/v1/gifs/search?q=tom+hiddleston&api_key=dc6zaTOxFJmzC&limit=20&rating=g

**Comment by dfinkler** [comment]
@paddycarey thanks for catching this. In a recent release we have insured that the pagination object's ints are ints and not strings.  Thanks for letting us know - going to close this issue now as resolved.
