### ISSUE TITLE
Random as parameter ?

### ISSUE THREAD

**Issue by ingouackaz** [Giphy/GiphyAPI#36]
Hi  @dfinkler !

I would like to get all gifs from a specific keyword and Trending GIFs randomly. 
Would it be possible to add a random parameter? Or do I have to sort them locally?

edit : Or a list of gifs randomly

**Comment by ingouackaz** [comment]
@namslam ?

**Comment by namslam** [comment]
Hey @ingouackaz !

Adding a random parameter to other existing endpoints is a great feature request! I'll make sure we chat about adding it internally. In the meantime check out sort=recent and sort=relevant, not so useful on trending but useful for search. 

http://api.giphy.com/v1/gifs/search?q=cats&api_key=dc6zaTOxFJmzC&sort=recent&fmt=html
http://api.giphy.com/v1/gifs/search?q=cats&api_key=dc6zaTOxFJmzC&sort=relevant&fmt=html

Hope this helps! 

Nam

**Comment by ingouackaz** [comment]
@namslam , Thank you for you quick answer :)
That helped a lot !

Let me know when this functionality is implemented.

Roger
