### ISSUE TITLE
Duration, tags and related GIFs

### ISSUE THREAD

**Issue by arpo** [Giphy/GiphyAPI#37]
I'm working on a project right now and need to know the duration of the mp4. I can get that by loading the clip and wait for metadata but that requires extra server round trips and slow things down. It would be great if I could get it from the JSON. Also tags of the clip, artist name and related gifs would be wonderful. Any comments on that?

**Comment by namslam** [comment]
Hey @arpo,

Thanks for reaching out! We're looking to add the duration of the mp4 to the JSON response in the upcoming months - stay tuned. Username/Artist names are publicly accessible if they're applicable (content from giphy.com/artists and giphy.com/partners) Tags and Related GIFs are currently reserved for approved partners apps only. You can send an email to nam@giphy.com with your app details if you'd like us to review your app for approval. Thanks!

**Comment by arpo** [comment]
Thanks @namslam that good news. I'm pretty sure you will like what I'm working on. More details later.
