### ISSUE TITLE
The difference between "fixed_height" and "fixed_height_downsampled" is not explained

### ISSUE THREAD

**Issue by SterlingOnLoop** [Giphy/GiphyAPI#38]
If I had to guess based on the names, I'd say `fixed_height` sounds like it clips while `fixed_height_downsampled` actually does scaling to preserve aspect ratio. But I'm not certain because the documentation is not clear.

Are there reasons to use one vs the other?

**Comment by namslam** [comment]
Hey @SterlingOnLoop,

We're working on updating our documentation to give a bit more explanation on what each image type is optimized for. fixed_height keeps the height at 200px (as a result, lowers the file size quite a bit) and fixed_height_downsampled keeps the height at 200px and also removes some frames in an attempt to lower the file size even further. 

Hope this helps!
-Nam
