### ISSUE TITLE
Upload API

### ISSUE THREAD

**Issue by gfpacheco** [Giphy/GiphyAPI#4]
I developed a gif app for Windows Phone, but I used the Tumblr API v1 to upload gifs. Since the shutdown of the API my app stopped sending gifs, and when it was starting to grow I stopped the development. I'm now returning to the project and I (as lots of developers) would like to send the gifs to Giphy. Do you have any plans on creating a upload API?

**Comment by RobertoUa** [comment]
Hi there @alexchung.
It's been 2 years. Do you currently support uploading via API. I've found that you have endpoint for uploading gifs (https://upload.giphy.com/v1/upload) but it requires `session_key`.
We're at Animatron developing an app to create animation and we support gif export. And now we need support for sharing to giphy very badly.
