### ISSUE TITLE
Random Image API endpoint now at tv.giphy.com?

### ISSUE THREAD

**Issue by btmash** [Giphy/GiphyAPI#40]
If you try to reach the endpoint 'http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=american+psycho', you get redirected to 'http://tv.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=american+psycho'. Any application that makes use of the random key may run into a CORS issue due to the redirect. Is this change going to affect the other APIs as well?

**Comment by namslam** [comment]
Hey @btmash,

Good catch! We're going to address this as soon as possible so it doesn't redirect. Thanks!

**Comment by dfinkler** [comment]
@btmash can you give us more details on which browser you're seeing a CORS issue on?  The tv.giphy.com should serve the same CORS headers as the api subdomain so there shouldnt be an issue, at least for the few browsers I have tested.  Thanks for the bug report - we're checking it out.

**Comment by btmash** [comment]
I want to clarify that tv.giphy.com gives the appropriate CORS headers and when I switched my api url to use tv.giphy.com, that resolved the issue. I'm not entirely sure, but that is what I seemed to be getting due to the redirect from api.giphy.com to tv.giphy.com. Hence, I just wanted to make sure accessing the random api requires sending a request to tv.giphy.com instead.

**Comment by dfinkler** [comment]
@btmash OK, we changed up the way we are routing this traffic behind the scenes and you should no longer see any redirects.  Feel free to use api.giphy.com/gifs/random without fear of being redirected :)

**Comment by z1c0** [comment]
I think this issue popped up again. Could you look into it?

**Comment by Sixuan** [comment]
My apologies for the inconvenience, there’s a fix in progress, this issue should be resolved in an hour. We will update once it’s out.

**Comment by Sixuan** [comment]
It should be resolved now. Let us know if there’s anything. Thanks for using/supporting our API.
