### ISSUE TITLE
Sharing giphy *.gif url for facebook doesn't get the same result as in giphy.com. What's is the secret?

### ISSUE THREAD

**Issue by codebusta** [Giphy/GiphyAPI#46]
Even though exact meta tags are used, the shared url doesn't scrape correctly, the gif isn't shown, while in giphy.com's facebook share option returns the expected result. Is there a some sort of agreement with facebook?

**Comment by namslam** [comment]
Hi @codebusta,

Thanks for reaching out! Giphy links are whitelisted to play on FB, you can learn more by visiting http://giphy.com/posts/how-to-share-giphy-gifs-on-facebook/. Hope this helps!

**Comment by codebusta** [comment]
That's what I thought, thanks, will be looking for the workaround then.
