### ISSUE TITLE
Giphy server doesn't support App Transport Security (iOS9)?

### ISSUE THREAD

**Issue by rajatrocks** [Giphy/GiphyAPI#47]
Even when trying to hit the https versions of the giphy API endpoints, and load media items via https, Xcode shows the following error: 

2015-09-10 18:34:33.858 TMI[11282:2366800] CFNetwork SSLHandshake failed (-9824)
2015-09-10 18:34:33.858 TMI[11282:2366874] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

More details on ATS here: http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

The workaround for now is to add giphy.com as an Exception Domain in the app's plist file. 
```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>giphy.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>                                    
        </dict>
    </dict>
```

**Comment by Pranoy1c** [comment]
same issue here too.

**Comment by dfinkler** [comment]
@rajatrocks @Pranoy1c thanks for the notice - we're looking into it

**Comment by dfinkler** [comment]
@rajatrocks @Pranoy1c can you check if you still need to add Giphy as an exception domain?  

I checked with our mobile developers and they are not having issues with ATS so long as they load everything via HTTPS.  I double checked our SSL configuration and we support all the required cipher levels as well as TLS 1.2.  

Please let us know if you're continuing to see the issue.
