### ISSUE TITLE
Random Endpoint Limit

### ISSUE THREAD

**Issue by austinkelleher** [Giphy/GiphyAPI#49]
I think it would be very useful to be able to hit the `random` endpoint with a limit, so we could receive more than one random gif at a time.

`/v1/gifs/random?limit=25&api_key=dc6zaTOxFJmzC`

**Comment by dfinkler** [comment]
@austinkelleher thanks for the suggestion.  We have it on the list!  I'll update the documentation when we added the limit feature to the random endpoint 

:+1:

**Comment by austinkelleher** [comment]
:+1:

**Comment by austinkelleher** [comment]
Any updates on this? Interested in utilizing this feature in my app. Thanks!

**Comment by namslam** [comment]
Hi @austinkelleher! Thanks for the follow up. It's still in our backlog but I'll follow up with the team today about it. Thanks!
