### ISSUE TITLE
Search by resolution

### ISSUE THREAD

**Issue by polskais1** [Giphy/GiphyAPI#50]
I'm working on an app that requires images of a specific resolution. The ability to be able to filter by image resolution or aspect ratio would be great!

```
/v1/gifs/random?height=300&width=300&api_key=dc6zaTOxFJmzC
```

**Comment by dfinkler** [comment]
:+1: awesome suggestion!  We're working on a bunch of new search related features and we have a number of new facets for search on the list - one of which is the image size.  Thanks for the suggestion and we'll update the docs once we have this feature ready
