### ISSUE TITLE
How to get fix size( width , height ) Giphies 

### ISSUE THREAD

**Issue by riksof-abdulrauf** [Giphy/GiphyAPI#51]
My task is to integrate Giphy in my application <a href="https://itunes.apple.com/us/app/flyerly-create-share-flyers/id344130515?mt=8">Flyerly</a>  . Right now I am getting trending Giphies using url

http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC

I want to get the trending Giphies of size (1240x1240) how can I do this ?

**Comment by namslam** [comment]
Hi @riksof-abdulrauf, thanks for reaching out. Right now we don't have a parameter you can add to filter by dimensions, but that's a great feature request. I will see if we can add that it. For now, every response includes the file dimensions and you can use that information to sort on your end. Hope this helps!

**Comment by riksof-abdulrauf** [comment]
Hi,
Any update on this ?

**Comment by timfrietas** [comment]
@riksof-abdulrauf there's still no committed timeline to offer filtering by or resizing to specific dimensions.  Filtering by image dimension is something we've considered--we may still offer it in the future, but probably not the near future.  

Resizing can result in poor quality GIFs if the original source is small and we resize them to be too large, so we currently do not have any plans to allow users to specify a new target size for a given GIF.

**Comment by riksof-abdulrauf** [comment]
@timfrietas: Ok very thanks for the reply
Waiting for this feature :)

**Comment by tbillington** [comment]
What about at least a way to get the same as the supplied input video file? (Seeing as being able to supply width/height is not likely to get added)

**Comment by jochemstoel** [comment]
Bump. I am looking for this feature too.

**Comment by sarbjit399** [comment]
I am still waiting 
![default5](https://user-images.githubusercontent.com/13548103/34267634-9d375b16-e6a3-11e7-9139-5dd4f9b8a32d.gif)

**Comment by farzan-dehbashi** [comment]
Bump! I am also looking for it.
