### ISSUE TITLE
Duplicate Access-Control-Allow-Origin on OPTIONS request

### ISSUE THREAD

**Issue by bendiksolheim** [Giphy/GiphyAPI#52]
Hello,

It seems you set the `Access-Control-Allow-Origin` header two times when I do an OPTIONS request towards an image. I have put the output from a CURL request demonstrating the issue at this gist: https://gist.github.com/bendiksolheim/80f47c96e41301f1e988 . `*, *` is not a valid value for this header, so my browser won't let my actually retrieve the image with an ajax request.

**Comment by pkkummermo** [comment]
+1

**Comment by bendiksolheim** [comment]
Has anyone had any time to look into this? I don't want to sound impatient, but we're quite eager to test Giphy in our product, and right now we can't really get any further because of this issue.

**Comment by namslam** [comment]
Hey @bendiksolheim,

Sorry for the delay here! Let me get this in front of our engineering team and I will keep you posted.

**Comment by bendiksolheim** [comment]
The response still has duplicate `Access-Control-Allow-Origin` header, but I thought I would just let you know that I got past the issue in another way. We had some global ajax configuration for jQuery which made all ajax requests demand a prefligth request. I removed this configuration for external services (as it was not really needed other than for internal services), and am now able to request images without a preflight request. So, the response is still technically wrong, but at least it works on my end :)

**Comment by dfinkler** [comment]
Thanks for the bug report @bendiksolheim - this should be fixed now.

**Comment by nickdandakis** [comment]
@dfinkler, looks like this bug is happening again but seems to return `Access-Control-Allow-Origin: *, *` only **some** times.

![image](https://cloud.githubusercontent.com/assets/7499386/19816771/a5316a28-9d16-11e6-8909-a2ad1494e03e.png)

![image](https://cloud.githubusercontent.com/assets/7499386/19816778/ae59ef08-9d16-11e6-847f-acecdbfd8562.png)
