### ISSUE TITLE
Public/Private state

### ISSUE THREAD

**Issue by ivankosdy** [Giphy/GiphyAPI#53]
Hi there!
Could you please add an attribute for gif video stating whether this video is private or public?
Thanks,
Ivan

**Comment by namslam** [comment]
Hi @ivankosdy,

Thanks for reaching out! Currently all gifs in our library are public. We do have private gifs however they are not accessible via the API. Hope this helps and let me know if you have any other questions!

Nam

**Comment by ivankosdy** [comment]
I set my video as private, my channel is private as well, but video is still accessible via GIF by ID call.

**Comment by namslam** [comment]
Ah I see, you are calling for the GIF directly. Let me follow up with the team to see our policy on private gifs via by the gif by ID call -- this may be something we'll patch up in the next release. If not, then your request for a public/private attribute is a good one and I'll keep you posted on that as well. Thanks @ivankosdy!

**Comment by namslam** [comment]
Hi @ivankosdy,

We just released a fix to address this issue. Private gifs should no longer be accessible via the GIF by ID call. If it's still happening for you let us know and we'll take another look. Thanks!
