### ISSUE TITLE
Wrong GIF size in metadata

### ISSUE THREAD

**Issue by pilot34** [Giphy/GiphyAPI#54]
Hi!

I'm developing iOS keyboard, where we are strongly limited in memory. So I'm choosing best GIF quality relying on the GIF's size from your metadata. There was some memory crashes in my app and I found, that for some GIFs Giphy shows wrong (smaller) size.

For example:
GIF http://api.giphy.com/v1/gifs/5xaOcLNaxyTBblwx5OU?api_key=dc6zaTOxFJmzC
Image `fixed_width`:

``` json
"fixed_width": {
        "mp4_size": "573573",
        "height": "113",
        "width": "200",
        "size": "166081",
        "mp4": "http://media1.giphy.com/media/5xaOcLNaxyTBblwx5OU/200w.mp4",
        "webp": "http://media1.giphy.com/media/5xaOcLNaxyTBblwx5OU/200w.webp",
        "webp_size": "211530",
        "url": "http://media1.giphy.com/media/5xaOcLNaxyTBblwx5OU/200w.gif"
      },
```

But when downloading this image http://media1.giphy.com/media/5xaOcLNaxyTBblwx5OU/200w.gif
It is 500kb, not 160kb.
![](https://monosnap.com/file/r6ppqTerKGZL9wiKJ001haYBYElrRd.png)
Size for `fixed_height` is wrong too (1.3Mb instead of 400kb)

Why is it so? How often can be such errors? Do we need perform HEAD-request every time to check size before downloading?

Thank you for great API.

**Comment by pilot34** [comment]
Many errors like this. About every 10th GIF has such error:

![](https://monosnap.com/file/lhZjyswEfzY4xbzz7XelrvUGk9JKru.png)

Some examples:

```
wrong size for url: http://media3.giphy.com/media/qbmjPU9cdaKkM/200.gif
in metadata 271029
in HEAD-request 810489

wrong size for url: http://media0.giphy.com/media/qbmjPU9cdaKkM/200w.gif
in metadata 185326
in HEAD-request 498893

wrong size for url: http://media1.giphy.com/media/pQ2GCFiK4CpKE/200.gif
in metadata 439901
in HEAD-request 1306132

wrong size for url: http://media3.giphy.com/media/bKes2jPPcyh0I/200.gif
in metadata 236720
in HEAD-request 780669

wrong size for url: http://media1.giphy.com/media/pQ2GCFiK4CpKE/200w.gif
in metadata 186905
in HEAD-request 552169

wrong size for url: http://media3.giphy.com/media/bKes2jPPcyh0I/200w.gif
in metadata 78582
in HEAD-request 281641

wrong size for url: http://media3.giphy.com/media/qbmjPU9cdaKkM/200.gif
in metadata 271029
in HEAD-request 810489

wrong size for url: http://media0.giphy.com/media/qbmjPU9cdaKkM/200w.gif
in metadata 185326
in HEAD-request 498893

wrong size for url: http://media4.giphy.com/media/yoJC2GCpCjMn0IddYI/200.gif
in metadata 357072
in HEAD-request 1529520

wrong size for url: http://media4.giphy.com/media/yoJC2GCpCjMn0IddYI/200w.gif
in metadata 357072
in HEAD-request 1529520

wrong size for url: http://media3.giphy.com/media/RGFL2W7ZJvoM8/200_d.gif
in metadata 117351
in HEAD-request 324976

wrong size for url: http://media4.giphy.com/media/2EO3gpbzj1VgQ/200w.gif
in metadata 453456
in HEAD-request 1489952

wrong size for url: http://media0.giphy.com/media/uOqyDdAwZcYFO/200.gif
in metadata 198598
in HEAD-request 595543

wrong size for url: http://media0.giphy.com/media/uOqyDdAwZcYFO/200w.gif
in metadata 143651
in HEAD-request 410699
```

**Comment by namslam** [comment]
Hi @pilot34,

Thanks for the heads up and sending everything over! We'll take a look into this and keep you posted on our findings -- definitely doesn't look normal. In the meantime, fixed width / height small assets (100px) are the best ones to use for mobile if performance is a concern. It's what many of the keyboards we power are using.

**Comment by namslam** [comment]
Hi @pilot34,

Just following up here -- we  are currently in the process of reanalyzing our gifs to correct any incorrect file size / dimensions in our library. Will keep you posted and thanks again for getting this in front of us!

**Comment by namslam** [comment]
Hi @pilot34,

Thanks for your patience on this one. Just wanted to send an update to say that we've audited our entire library and have found the list of metadata discrepancies to be corrected. Will follow up once more when we run the script to fix all the incorrect metadata.

**Comment by pilot34** [comment]
👍

**Comment by pilot34** [comment]
I think we can close that, thank you
