### ISSUE TITLE
Understand Rating types 

### ISSUE THREAD

**Issue by thelegend94** [Giphy/GiphyAPI#55]
Hi 
Please can you explain what rating types y,g and others mean?
I really don't know each type talking about what !!

**Comment by namslam** [comment]
Hi @thelegend94,

We follow the same structure as the MPAA rating system and support the following ratings: Y, G, PG, PG-13, and R. You can learn more about each rating here: http://www.mpaa.org/film-ratings/

To add a rating to your API request, simply add &rating=<rating>. Here's an example search for 'funny cat' gifs that are rated up to PG-13. Please note that by adding a rating, the results will include that rating and everything below it. So PG-13 will include PG, G, and Y gifs as well.

http://api.giphy.com/v1/gifs/search?q=funny+cat&api_key=dc6zaTOxFJmzC&rating=pg-13

Hopefully this is helpful and let me know if you have any other questions. Thanks!

**Comment by thelegend94** [comment]
Thank you Nam. I read about rating types and understand what means.
But what about "Y" types because not listed in MPAA infograhic http://www.mpaa.org/wp-content/uploads/2013/11/film_ratings1.jpg ?

**Comment by namslam** [comment]
Hi @thelegend94,

Y is strictly "animated" content only, ie cartoons and illustrations. Apologize for not being clear on that one earlier. Hope this helps!

Nam

**Comment by thelegend94** [comment]
Thanx Nam for this info, you should add this info documentation.

**Comment by namslam** [comment]
good point @thelegend94! we will make plans to update our docs with this and any other missing items.

**Comment by VictorioBerra** [comment]
@namslam I still do not see "Y" in the list of ratings. Also, do you pass PG-13 or PG13 without hyphen?
