### ISSUE TITLE
HTTP urls when requesting through HTTPS

### ISSUE THREAD

**Issue by pkkummermo** [Giphy/GiphyAPI#56]
We're experiencing that the url given for the gifs in the API is with HTTP when we ask through HTTPS. Before we were given HTTPS urls implicitly. Is this a bug or should we start start replacing HTTP with HTTPS in the urls? Is there a flag for asking for HTTPS?

**Comment by hatutah** [comment]
@pkkummermo Sorry for the inconvenience. Can you provide an example of the URL/method for which you are experiencing this issue?

**Comment by pkkummermo** [comment]
Sure:

```
Request URL:https://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC
```

``` 
"fixed_width_small":{
               "url":"http:\/\/media2.giphy.com\/media\/26tP2R0RSoHylXp6M\/100w.gif",
               "width":"100",
               "height":"57",
               "size":"85222",
               "mp4":"https:\/\/media2.giphy.com\/media\/26tP2R0RSoHylXp6M\/100w.mp4",
               "mp4_size":"8882",
               "webp":"https:\/\/media2.giphy.com\/media\/26tP2R0RSoHylXp6M\/100w.webp",
               "webp_size":"49462"
            },
            "fixed_width_small_still":{
               "url":"http:\/\/media2.giphy.com\/media\/26tP2R0RSoHylXp6M\/100w_s.gif",
               "width":"100",
               "height":"57"
            }
```

The problem has been fixed as far as I can see. The problem was that the images url was given with http and not https. This would break the https/ssl contract with the page making it insecure. I made a temporary fix on my end as well to ensure that the url we used was https.

**Comment by namslam** [comment]
Hey @pkkummermo,

Thanks for the additional info and glad to hear the issue was resolved for you. We're going to do a global audit to ensure all of our endpoints respond with the proper response. Again, thanks for keeping an eye out!
