### ISSUE TITLE
#mashup #echo #weather support in API?

### ISSUE THREAD

**Issue by mattrobenolt** [Giphy/GiphyAPI#57]
So Slack does this cool thing with giphy where you can do `/giphy #mashup thing other-thing`

It seems they support #{mashup,echo,weather}, but I can't figure out how to do this purely through the giphy API.

Are they using something not supported publicly?

They spit out urls like, giphy-caption.gif, giphy-overlay.gif, and giphy-glitter.gif coming from media\d.giphy.com. So they're not doing anything special on their end, and it's coming from you. :)

Thanks!

**Comment by namslam** [comment]
Hi @mattrobenolt,

Thanks for reaching out and yes these are our (secret) # integrations! We have dozens that we're currently working on (try /giphy #enhance <insert image or gif link of a person> or ask #8ball a question), however they are not yet publicly accessible via the API at this time. That said, we're working fast to make them available to any developer / app early next year.

Best way to keep in touch with us is either by watching this repo or following us on twitter (https://twitter.com/giphy)

Hope this helps and let me know if you have any other questions.
Nam

**Comment by mattrobenolt** [comment]
Awesome, thanks for the info. I'll keep a lookout. :)
