### ISSUE TITLE
Documentation mistakes

### ISSUE THREAD

**Issue by 2xAA** [Giphy/GiphyAPI#58]
It's nothing too major but there are a couple of small mistakes in the docs:

https://github.com/giphy/GiphyAPI#path-7
*The path is listed as "/v1/sticker/random" when it should be "/v1/stickers/random"*

https://github.com/giphy/GiphyAPI#parameters-7
*The parameters do not mimic the example parameters: 'q' differs from 'tag'.*

The second "mistake" does still work, but it is misleading.

Thanks for the great API and service!

**Comment by dfinkler** [comment]
thanks for making us aware of these mistakes, we'll update the docs shortly @2xAA

**Comment by dfinkler** [comment]
@2xAA :+1: 

thanks for the note we've updated our documentation to correct these mistakes
