### ISSUE TITLE
Missing response properties documentation

### ISSUE THREAD

**Issue by rascarlo** [Giphy/GiphyAPI#59]
- slug
- source_tld
- source_post_url
- looping

Calls are now returning also these properties which are not documented on https://github.com/Giphy/GiphyAPI
Nothing major, just to let you guys know. Thank you for the API.

**Comment by namslam** [comment]
@rascarlo thanks for the heads up! We'll be updating the documentation soon

**Comment by dfinkler** [comment]
@rascarlo thanks for the note! :+1:   
we've updated the documentation to include the missing properties.

**Comment by rascarlo** [comment]
Thank you guys. Giphy is awesome!
