### ISSUE TITLE
AFNetworking Support

### ISSUE THREAD

**Issue by jakobsa** [Giphy/GiphyAPI#60]
lib depends on old version of AFNetworking (~> 2.3.1), this breaks compatibility to projects wanting to use a more recent AFNetwoking version:

[!] Unable to satisfy the following requirements:
- `AFNetworking/Serialization (= 2.6.1)` required by `Podfile.lock`
- `AFNetworking/Serialization (= 2.6.1)` required by `AFNetworking (2.6.1)`
- `AFNetworking/Serialization (= 2.6.1)` required by `AFNetworking/NSURLConnection (2.6.1)`
- `AFNetworking/Serialization (= 2.6.1)` required by `AFNetworking/NSURLSession (2.6.1)`
- `AFNetworking/Serialization (~> 2.3.1)` required by `Giphy-iOS (0.1.0)`

**Comment by dfinkler** [comment]
Hi @jakobsa I suspect this issue is meant for another project :

https://github.com/heyalexchoi/Giphy-iOS

Giphy-iOS is a 3rd party library which is not maintained by Giphy however I'm sure if you get in touch with heyalexchoi they'll be able to help.
