### ISSUE TITLE
Add GIFs API Request

### ISSUE THREAD

**Issue by polykrom** [Giphy/GiphyAPI#61]
Hi,

I just wonder if you plan to release an API that we can use to automatically add GIFs to a Giphy Account ?
I'm myself author of an online GIF editor and it would be nice when publishing the generated GIF to push it to Giphy through an API.

What do you think ?

Thanks :)

François

**Comment by namslam** [comment]
Hi @polykrom! We have an upload endpoint that we plan to make public soon! If you send me an email to nam@giphy.com I can give you access so you can upload GIFs to your Giphy account. Looking forward to working together!
