### ISSUE TITLE
Is the Random endpoint really random?

### ISSUE THREAD

**Issue by dustedrob** [Giphy/GiphyAPI#62]
I'm getting repeats when using the random endpoint fairly often; approximately once every ten queries. Normal queries yield hundreds of possible results so it's very weir that the random result would appear as often as it does.

Can you share your random algorithm?

**Comment by namslam** [comment]
Hi @dustedrob,

Hmm that shouldn't be the case as we do an evenly weighted distribution of randomness with the Random endpoint. Can you share with me an example request you're making so we can try and duplicate the repeats?
