### ISSUE TITLE
Add a way to specify needed fields or image sizes to return

### ISSUE THREAD

**Issue by vovkab** [Giphy/GiphyAPI#64]
Response seems like pretty big, especially when you trying to do search while you type.
So it would be nice to have a way to specify a list of fields to return.
(Or at least specify list of sizes to return, to make response as small as possible)

For example, let's say I only need giphy `id` and `fixed_width`, I can pass something like:
`props=id,images@fixed_width`

and get this response:

```
{
    "data": [
        {
            "id": "feqkVgjJpYtjy",
            "images": {
                "fixed_width": {
                    "url": "http://media0.giphy.com/media/feqkVgjJpYtjy/200w.gif",
                    "width": "200",
                    "height": "90",
                    "size": "115885",
                    "mp4": "http://media0.giphy.com/media/feqkVgjJpYtjy/200w.mp4",
                    "mp4_size": "31919",
                    "webp": "http://media0.giphy.com/media/feqkVgjJpYtjy/200w.webp",
                    "webp_size": "122600"
                }
            }
        },
        ...
    ]
}
```

**Comment by namslam** [comment]
Hi @vovkab,

Great suggestion! I will bring it to the team and see if we can add that to our roadmap. Will keep you posted

**Comment by vovkab** [comment]
@namslam thanks!

Should we keep ticket open until you make a decision?

**Comment by namslam** [comment]
Oops didn't mean to close it!

**Comment by namslam** [comment]
Hi @vovkab!

We've decided to include this in our roadmap and will probably be able to get this out in the upcoming months. Going to mark this ticket as closed for now, since this is a feature request. Make sure to watch our public docs to be notified of any changes. Thanks!
