### ISSUE TITLE
upload endpoint

### ISSUE THREAD

**Issue by jmsaavedra** [Giphy/GiphyAPI#66]
Quick question: Any plans to add any upload endpoints? I assume this would also require some authentication endpoints to upload to a specific user account...

Thanks for any info --

**Comment by rascarlo** [comment]
That would be awesome

**Comment by namslam** [comment]
Hi @jmsaavedra @rascarlo,

Nice timing! We've had private upload endpoints for some time now and are looking to make them public in the upcoming month. Stay tuned!

**Comment by namslam** [comment]
Hi @jmsaavedra @rascarlo,

Going to close this ticket now since this is a feature request. Make sure to watch our public docs to be notified of any changes!

**Comment by rascarlo** [comment]
Thank you
