### ISSUE TITLE
Smallest Giphy size in images array

### ISSUE THREAD

**Issue by ritesh-nitw** [Giphy/GiphyAPI#67]
I need to display all the trending animated giphies in a matrix. 
To display the preview, I am planning to use the giphies with smallest size, as all the images will load quickly.
What is the smallest giphies size(memory-wise) in image array? 
Tried observing few results and it seems 'fixed_width_small' has smallest size.
Can I assume '**fixed_width_small**' always  to be the smallest giphies?

Apologies if I missed something obvious.

**Comment by namslam** [comment]
Hi @ritesh-nitw,

Yes fixed_width_small and fixed_height_small are your 2 best options! You can get a breakdown of our various renditions here: https://github.com/Giphy/GiphyAPI#rendition-guide.You can also use downsampled which minimizes the gif to just 6 frames, making it even more performant. We use that on our mobile website, which you can preview by visiting giphy.com on your phone. Hope this helps!
