### ISSUE TITLE
GIF's from specific channel

### ISSUE THREAD

**Issue by andrey-lisovskiy** [Giphy/GiphyAPI#69]
Hello! In my iOS app I need to retrieve GIF's from specific channel.
How can I do this with your API?

**Comment by rascarlo** [comment]
@andrey-lisovskiy it looks like the giphy api doesn't expose any way to filter specific channel.
https://github.com/Giphy/GiphyAPI#overview 
Search
GIF by id
GIFs by id
Translate
Random
Trendi

**Comment by dfinkler** [comment]
hi @andrey-lisovskiy can you elaborate a bit on what you mean by "channel"?  how does a channel differ from a tag?

**Comment by andrey-lisovskiy** [comment]
Hi @dfinkler 
For example, I need to retrieve all gifs from next channel:
http://giphy.com/channel/jennirl
How can I do this?

**Comment by dfinkler** [comment]
Hi @andrey-lisovskiy we have this functionality enabled as a private endpoint and are currently working on building out a public channel API which we'll open up in the coming months!

**Comment by heymynameisrob** [comment]
Any update on this being introduced to the public API?

**Comment by timfrietas** [comment]
Hi @heymynameisrob,  

It's still coming :)  We don't have exact date yet but soon!
