### ISSUE TITLE
Is it possible to use `%2B` instead of `+` literal

### ISSUE THREAD

**Issue by ndelvalle** [Giphy/GiphyAPI#71]
I tested using both, and the api responded the same data. But I would like to make sure that this behaviour will persist.

Testing examples that used:

`http://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=person%2Bfunny`
`http://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=person+funny`

**Comment by namslam** [comment]
Hi @ndelvalle,

You should have no problem using '%2B' instead of '+'. Alternatively you can use '%20' as a space as well to receive the same results. Here's an example: http://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=person%20funny. Hope this helps!
