### ISSUE TITLE
Checking a GIFs tags

### ISSUE THREAD

**Issue by TetraEtc** [Giphy/GiphyAPI#74]
How do I use `gif_by_id` to check the tags of a GIF of a given ID?

**Comment by namslam** [comment]
Hi @TetraEtc,

Thanks for getting in touch! Currently we only allow approved partners to access Tags via the API. An approved partner must be able to pass all the questions on api.giphy.com/submit. If you want, you can email nam@giphy.com with your proposed project and I can see if we can approve it so you can access tags while you test. 

Hope this helps!
Nam
