### ISSUE TITLE
Sticker Trending Endpoint - "s" parameter

### ISSUE THREAD

**Issue by TetraEtc** [Giphy/GiphyAPI#75]
In the documentation for the Sticker Trending Endpoint you mention that you can have the "s" parameter to translate the given phrase into a GIF.

From what I can see this doesn't actually do anything though

E.G/.: http://api.giphy.com/v1/stickers/trending?api_key=dc6zaTOxFJmzC&limit=4&fmt=html&s=cats

**Comment by namslam** [comment]
Hi @TetraEtc,

Thanks for the note! This looks to be a mistake in our documentation - nice catch, I'll fix it now. Right now trending stickers is a curated feed that doesn't support the search parameter. Hope this helps!
