### ISSUE TITLE
Add community favorite gifs such as tubgirl, goatse, etc..

### ISSUE THREAD

**Issue by raandy** [Giphy/GiphyAPI#77]
There is a lack in-demand gifs and the giphy community feels they are unable to express themselves when there is a gap of gif. I'm talking tubgirl, goatse. How will the community cope without these items in our arsenal?

**Comment by timfrietas** [comment]
Hi raandy,

We currently don't support NSFW results in general Giphy search results or any of our integrations, but I am sure I have seen them in other places on the internet

<iframe src="//giphy.com/embed/xEox2PQ6frFiE" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/butts-athletic-xEox2PQ6frFiE">via GIPHY</a></p>

Closing this as it's not a technical issue.
