### ISSUE TITLE
Upload Response Model - Gif Id not named correctly

### ISSUE THREAD

**Issue by discoaaron** [Giphy/GiphyAPI#79]
Helloo,

The Upload response model on this page tells us that the Id of the gif is named 'gif_id'. However in the actual response the name is just 'id'

I use the copy and 'paste JSON as class' option in Visual Studio where this issue became apparent. 
Small issue though, in an otherwise easy to use API!

[EDIT]
Sorry I just realised the entire model is wrong! Not just the id tag.

API Spec on github
{"meta":{"gif_id":"your_new_gif_id","status":200,"msg":"OK"}}

Actual Response
{"data":{"id":"3o72FcX9tNOOR3428o"},"meta":{"status":200,"msg":"OK"}}

[Snippet from Github]
![image](https://cloud.githubusercontent.com/assets/4475215/16030537/0967e9c2-3246-11e6-8140-5d7e4c3397c8.png)

[Actual Response]
![image](https://cloud.githubusercontent.com/assets/4475215/16030580/b678e472-3246-11e6-97e5-d9d8159cc267.png)

**Comment by namslam** [comment]
Hey @discoaaron,

Nice catch! The Upload API docs have been updated. Thanks!

**Comment by discoaaron** [comment]
No worries! 
Happy to contribute :+1:
