### ISSUE TITLE
Is it possible to create a gif using the api?

### ISSUE THREAD

**Issue by arieljannai** [Giphy/GiphyAPI#80]
Like what you have [here](http://giphy.com/create)

**Comment by TetraEtc** [comment]
Oh this would be very cool!

**Comment by ColaColin** [comment]
From Javascript you can with a function like this:

`var uploadGIF = function(blob, progressListener, completeListener) {
	var form = new FormData();
// production deployments would need a production key obviously
	form.append("api_key", "dc6zaTOxFJmzC");
	form.append("file", blob);
	
	$.ajax({
		url: 'http://upload.giphy.com/v1/gifs',
		type: 'POST',
		xhr : function() {
			var myXhr = $.ajaxSettings.xhr();
			if (myXhr.upload) {
				myXhr.upload.addEventListener('progress', progressListener, false);
			}
			return myXhr;
		},
		data: form,
		cache: false,
		contentType: false,
		processData: false,
		success: function(result) {
			if (result && result.data && result.data.id) {
				completeListener(result.data.id); // the listener gets the id of the uploaded gif
			} else {
				console.log("ERROR uploading gif", arguments);
				completeListener(null);
			}
		},
		error: function() {
			console.log("ERROR uploading gif", arguments);
			completeListener(null);
		},
	});
};`

**Comment by faisalsahil** [comment]
How to create gif from url in rails?

**Comment by timfrietas** [comment]
@arieljannai Not yet!  It might be something we release in the future!
