### ISSUE TITLE
GIF length limit?

### ISSUE THREAD

**Issue by ColaColin** [Giphy/GiphyAPI#81]
From the FAQ on giphy.com I was under the impression that the limits for gifs are "below 100mb and less than 15s long". Is this really true? Especially the length?
I uploaded this, first via API and then via the webpage upload. Both worked fine:
https://giphy.com/gifs/3o6gDXBVctFi1mjR6g

600 frames, each at 100ms. So 60s long. Clearly above the length limit?

What's wrong here? The FAQ information? Or is this a bug in the verification of the limits?
If there is no 15s limit anymore I'll skip implementing a check for it on my side, so I'd like to know what is the limit for gif size/length I am allowed to upload?

**Comment by timfrietas** [comment]
Hi @ColaColin,

Thanks for reporting this.  I am unable to reproduce this on my side right now but I am leaving this open so that we can perform broader testing to make sure there's not an edge case where things can get around the upload restraint checks.

**Comment by ColaColin** [comment]
What is the official limit? The FAQ talks of 15s, but in other places (I think it was the API documentation) it only said "below 100mb".

**Comment by timfrietas** [comment]
@ColaColin Through either Giphy.com upload or API upload we will cut you off at 100MB no matter the source (video, GIF).  The 15 seconds length applies to a video source and should apply to both Giphy.com and API upload as well.

So it possible to have a GIF of your length as long as it is uploaded as a GIF.  If you uploaded a video of that length to get converted to a GIF it would fail.

Hope that clarifies things; we will update our documentation to be a little clearer on these points.  Thanks for asking the question!

Let me know if you still need assistance.

**Comment by ColaColin** [comment]
Thanks, that's the answer I hoped for. The phrasing in the FAQ then just confused me. :)

**Comment by psyklon-project** [comment]
I think I just faced the same issue. I tried to upload some GIF files with 128 frames, but all of them being cut. I don't know if it's a filesize or an animation length issue, but the loop is clearly broken. My original files are around 10Mb, and they are GIF files. Here are the files I tried to upload:

Original: http://psyklon.com/bakteruim.gif
Giphy: https://giphy.com/gifs/bacteria-microlife-3YJ1xLFCj13xSvtntI

Original: http://psyklon.com/bakteruim2.gif
Giphy: https://giphy.com/gifs/fractal-bacteria-microlife-AgV14NZ7cROL9n0xwL

Original: http://psyklon.com/bakteruim3.gif
Giphy: https://giphy.com/gifs/fractal-bacteria-microlife-ORDZ0ses0HPQe6YYt2

Can I ask what's went wrong here, and how can I upload them in full length?
