### ISSUE TITLE
Search results from API don't match the sites identical query on gipht.com

### ISSUE THREAD

**Issue by Philro** [Giphy/GiphyAPI#82]
Hey Guys, The results on the site are so much better for me than what I get in the API. Is there a list of query params or other ways to refine search?
1) can i refine on giphy's with NO text?
2) ca i refine on stills only?
3) can i refine on minimum original resolution ( size) ?

Repro: on the site search for Donald Trump
in the api use q=donald trump  (or q=donald+trump) 

 the results dont match.

thanks!

**Comment by timfrietas** [comment]
Hi @Philro,

As far as #1 goes the answer is currently no. 

For #2 the answer is yes; we expose stills as part of search, for example `original_still`.  The JSON hierarchy to the first result is `data[0].images.original_still`

For #3, `fixed_height` is 200px high, `fixed_width` is 200px wide, and ` fixed_height_small` and `fixed_width_small` are 100px respectively. 

Concerning what is on the home page vs what you are getting, I am unable to reproduce.  For example, http://api.giphy.com/v1/gifs/search?q=donald+trump&api_key=dc6zaTOxFJmzC&fmt=html and http://giphy.com/search/donald-trump appear to be identical.

Let me know if you have any more questions!
