### ISSUE TITLE
how many uploads allowed at same time ?

### ISSUE THREAD

**Issue by thelegend94** [Giphy/GiphyAPI#84]
Hi
If I have 100 user want to upload gifs by one upload key at same time, is this allowed ? or what is max number?
Also how many upload key requests can make?

**Comment by timfrietas** [comment]
Right now there is a one-to-one relationship between an upload key and a user account; if your app is CoolGIFApp and CoolGIFApp is the Giphy username associated with your upload API key all GIFS are uploaded under the username "CoolGIFApp".  We hope to offer more options in the future, like the ability to upload on behalf of other Giphy users.

If instead you just mean end users of your application (and not Giphy users) then there is no limit on the origin of the upload, but there is a hard limit of total GIFs allowed each day.

Right now we limit uploads to 1000 per day per API key; we make exceptions to this limit on a case-by-case basis.  Email api@giphy.com if you believe you have an exceptional use case and we will review and work with you to determine if your limit can be increased.
