### ISSUE TITLE
/giphy #caption "caption text" giphyGifUrl

### ISSUE THREAD

**Issue by HomerGaidarski** [Giphy/GiphyAPI#86]
When I use the /giphy #caption command in slack using a direct giphy gif url, it posts the gif twice, once as the original gif and a second time as the gif + the caption.

**Comment by HomerGaidarski** [comment]
Example:
/giphy #caption "is this a bug?" https://media.giphy.com/media/26BRzbgYCyhMcXXZC/giphy.gif

**Comment by HomerGaidarski** [comment]
Actually it seems to also happen with media urls that are not giphy urls, but sometimes one of the gifs is not the gif from the media url, but rather a random gif.

Example:
/giphy #caption "is this a bug" https://s-media-cache-ak0.pinimg.com/236x/28/37/d4/2837d4aa7e9ceba6b171bb133cf592a5.jpg

**Comment by timfrietas** [comment]
Thanks for reporting this!  Yep, we should change this so you only get returned the captioned version.

**Comment by namslam** [comment]
@HomerGaidarski Just following up to let you know this has been resolved, thanks!

**Comment by 2018happynewyear** [comment]
<a href="https://www.happynewyear2018images.com/2018-best-new-year-unique-messages-greeting-cards-wishes-family-friends-loved-ones/" >New Year’s Greetings For your Boyfriend</a>,<a href="https://www.happynewyear2018images.com/2018-best-new-year-unique-messages-greeting-cards-wishes-family-friends-loved-ones/" >New Year’s Greetings For Your Girlfriend</a>,<a href="https://www.happynewyear2018images.com/2018-best-new-year-unique-messages-greeting-cards-wishes-family-friends-loved-ones/" >New Year Wishes For Best Friend</a>,<a href="https://www.happynewyear2018images.com/2018-best-new-year-unique-messages-greeting-cards-wishes-family-friends-loved-ones/" >Cute Happy New Year Card</a>,<a href="https://www.happynewyear2018images.com/2018-best-new-year-unique-messages-greeting-cards-wishes-family-friends-loved-ones/" >2018 New Year Messages</a>
