### ISSUE TITLE
Channel / partner search

### ISSUE THREAD

**Issue by Catwashere** [Giphy/GiphyAPI#87]
List channel or partner gifs, add also a search inside them.

This exists in the website
Partner - http://giphy.com/100soft/2?is=1&json=true
Channel - http://giphy.com/channel/vivillrockyou/2?is=1&json=true

**Comment by timfrietas** [comment]
Hi @Catwashere,

We have this in our product roadmap backlog.  We don't yet have a date to advertise, but look for this sort of feature to come in the future.
