### ISSUE TITLE
Search limit on offset?

### ISSUE THREAD

**Issue by yalesong** [Giphy/GiphyAPI#88]
Search API with public beta key appears to have a limit on the offset term.

Search on a keyword `obama` returns the total_count 10131:
[http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC](http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC)

Setting the offset term to 4974 returns 25 items:
[http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC&offset=4974](http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC&offset=4974)

But setting the term to 4975 returns zero item:
[http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC&offset=4975](http://api.giphy.com/v1/gifs/search?q=obama&api_key=dc6zaTOxFJmzC&offset=4975)

@katebell483 mentioned in #31 that setting the term to 26024 would work with `cat`:
[http://api.giphy.com/v1/gifs/search?q=cat&limit=25&offset=1&offset=26024&api_key=dc6zaTOxFJmzC](http://api.giphy.com/v1/gifs/search?q=cat&limit=25&offset=1&offset=26024&api_key=dc6zaTOxFJmzC)
But that link also returns zero item.

Does the public beta key have a limit on the offset? Is there any way we can get more results?

**Comment by yalesong** [comment]
Anyone?

**Comment by namslam** [comment]
Hey @yalesong!

Thanks for your note and really apologize for the delay! There should be no limitations on the public beta key with regards to the `offset` parameter. I was able to reproduce what you're seeing with a non-public API key and it appears to be a bug on our side. I'll get the engineering team to take a look at this and we'll keep you posted!

Nam

**Comment by timfrietas** [comment]
Hi @yalesong,

We did in fact change this limit recently after all.  It should be reflected in the API docs shortly.  It is currently set to 5000.  This limit is being added to our documentation soon, and we are sorry for the inconvenience!

**Comment by codart1** [comment]
I've spent my whole day figuring it out this strange behaviour. Pls add more info to doc so it can help prevent wasting time for any other dev

**Comment by vardrop** [comment]
[still not added to the documentation](https://developers.giphy.com/docs/) @timfrietas @namslam

**Comment by seanmthompson** [comment]
Just also going to add that its now almost 2020 and the documentation still hasn't been updated.

**Comment by AvaN0x** [comment]
Well I guess there's still nothing on the documentation ... :/

**Comment by ojoven** [comment]
I come from the future, it's 2025, our 6th year of confinement and this hasn't been added to the documentation yet.

**Comment by ssagar19** [comment]
came from 2030 , documentation hasn't been updated yet

**Comment by shwetaatgiphy** [comment]
Hi All,

Max value for `&offset` and `&limit` can be found here in our documentation: [Trending Endpoint](https://developers.giphy.com/docs/api/endpoint#trending) / [Search Endpoint](https://developers.giphy.com/docs/api/endpoint#search).
If you've observed different behavior, please feel free to create a new issue or write in to developers@giphy.com 
Hope this helps.
