### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by ivankosdy** [Giphy/GiphyAPI#89]
Hi there!

I'm getting empty username in "Get GIF by ID" call response for some older videos.
For example: http://api.giphy.com/v1/gifs/feqkVgjJpYtjy?api_key=dc6zaTOxFJmzC

Why is it so?

Thanks

Ivan

**Comment by timfrietas** [comment]
Hi @ivankosdy,

A fairly large percentage of our GIFs have no user associated with them because they were uploaded anonymously.

**Comment by ivankosdy** [comment]
Yeah but for example my video (afaik wasn't uploaded anonymously) is missing username too
http://giphy.com/gifs/vaskyjugend-26tP7Q1VGW0UcCr4c
http://api.giphy.com/v1/gifs/26tP7Q1VGW0UcCr4c?api_key=dc6zaTOxFJmzC
even though it's listed as public and it's on my public channel...

**Comment by timfrietas** [comment]
Oh, interesting.

I reopened this, thanks @ivankosdy!  We shall take a look.

**Comment by ivankosdy** [comment]
I checked it now and it seems to be working for video mentioned before...
Is this still an issue or it has been resolved?
Thanks!
