### ISSUE TITLE
Support Google AMP(?)

### ISSUE THREAD

**Issue by pribeh** [Giphy/GiphyAPI#90]
Hey Guys,

Anyone interested in helping to support Google Amp? Myself and others over at the AMP queue are wondering. Thanks!

https://github.com/ampproject/amphtml/issues/1591#issuecomment-241069447

**Comment by timfrietas** [comment]
Hey Pribeh,

I just commented on your project in Github.  I'm going to close this issue because we track feature requests separately, but we can figure it out over in your project or you can hit me up with the contact info I provided.  Thanks!
