### ISSUE TITLE
Empty data responses

### ISSUE THREAD

**Issue by tomasvts** [Giphy/GiphyAPI#93]
If I request

> http://api.giphy.com/v1/gifs/search?q=funny+cat&api_key=dc6zaTOxFJmzC   

I get

> {"data":[],"meta":{"status":200,"msg":"OK"}}

Its just me?

**Comment by moklick** [comment]
same here. I only receive empty responses. I can't find a status site or anything.

**Comment by hatutah** [comment]
We are experiencing a site outage. We should be back online momentarily. Apologies for the inconvenience.

**Comment by tomasvts** [comment]
Aaand Is working again

Thank you!
