### ISSUE TITLE
how to paging data

### ISSUE THREAD

**Issue by binbin269x** [Giphy/GiphyAPI#95]
how to paging data? i cannot load more data

**Comment by timfrietas** [comment]
Hi @binbin269x,

Can you share the query you are making?

**Comment by binbin269x** [comment]
@timfrietas api trendings and search : http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC
How to loadmore data. pls help me

**Comment by timfrietas** [comment]
Hi @binbin269x,

Use the offset parameter to do this.  For example:

> http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&offset=1

Will return the next 25 results.  The limit is set to 25 by default but this can also be adjusted with the limit parameter.  For example, the following request would return you GIFs 51-100 in the trending feed

> http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&limit=50&offset=1

Let me know if you have any further questions!  More info of course can be found at https://github.com/Giphy/GiphyAPI.  Good luck!
