### ISSUE TITLE
GIF ID 3oGNDhc5QwFlI6v55e is returning invalid sizes

### ISSUE THREAD

**Issue by MartinStava** [Giphy/GiphyAPI#96]
Please see: http://api.giphy.com/v1/gifs/3oGNDhc5QwFlI6v55e?api_key=dc6zaTOxFJmzC

The API returns invalid sizing information as well as missing mp4 link. Our app is crashing because of that right now. Can you please have a look at it? Thanks

**Comment by timfrietas** [comment]
Hi Martin,

This should be resolved now.  Thanks for letting us know!
