### ISSUE TITLE
Searching by tags?

### ISSUE THREAD

**Issue by ravelab** [Giphy/GiphyAPI#97]
Hi, is it possible to search by tags?  Let's say I wanna search "Tom Cruise", but I don't want any results for "Tom" or "Cruise", how do I do it? Thx.

**Comment by timfrietas** [comment]
We don't support exact tag search matching yet.  Right now there are a lot of factors in our search algorithm and although exact matches are the likely to appear first in search results there's no guarantee, and there's not yet a parameter to limit results to exact matches.

It's a good idea and I've put an item in our feature backlog to consider adding it in the future.

Thanks for the suggestion!
