### ISSUE TITLE
GIF ID l4hmG0d10YtQ8W2iI is returning invalid sizes

### ISSUE THREAD

**Issue by MartinStava** [Giphy/GiphyAPI#98]
It's happening again, please see: http://api.giphy.com/v1/gifs/l4hmG0d10YtQ8W2iI?api_key=dc6zaTOxFJmzC

**Comment by MartinStava** [comment]
Same here: http://api.giphy.com/v1/gifs/l396EheVvfLiM0Ba0?api_key=dc6zaTOxFJmzC

**Comment by MartinStava** [comment]
Here again: http://api.giphy.com/v1/gifs/l396EheVvfLiM0Ba0?api_key=dc6zaTOxFJmzC

**Comment by timfrietas** [comment]
This is now resolved!  Thanks for reporting this.
